(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgZB4QgJgLAAgPQAAgQAJgKQAKgKAPAAQARAAAJAKQAIAKABAQQgBAPgIALQgJAKgRAAQgPAAgKgKgAgRAkQgGgDgCgKQgCgHgBgTIgFh1IAQgHQALgCAHAAQAPAAAIAIQAHAGAAAPIgEBkQgBATgEAPIgDACIgHADIgMABQgHAAgKgEg");
	this.shape.setTransform(755,38.8,0.667,0.667);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgaBdQgTgGgNgNQgMgMgJgTQgIgUAAgYQAAgbAIgRQAIgUAMgKQAMgMARgGQARgFAPAAQATgBAQAHQAQAGALALQALALAHAOQAGAQAAARQAAAOgHAFQgIAIgLABIhYAPQAEALAMAHQAMAHAPAAQAPAAANgFQAOgDAIgGQAGAFADAGQAEAHAAAHQAAASgPAJQgMAGgOADQgMABgPAAQgUABgSgHgAgMgvQgGACgEAGQgEAFgCAFQgCAHAAAFIA8gKQAAgIgIgIQgGgIgOAAQgIAAgGAEg");
	this.shape_1.setTransform(744.8,40.8,0.667,0.667);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgpBhQgGgCgEgDQgFgDgCgGQgCgHAAgJIAAhyQAAgJACgHQAEgGAFgFIAOgJIAmgMIAVgCQARAAAKAHQAKAIAAAQQAAAFgBAFIgEAKIgPAAIgeAGIgLAEIAACCIgLADIgQABg");
	this.shape_2.setTransform(733.7,40.7,0.667,0.667);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AglBdQgSgIgMgMQgNgNgGgSQgHgUAAgWQAAgVAHgUQAHgRAMgOQAMgNASgGQASgIATABQAVgBASAIQASAHALAMQAMANAIATQAGASAAAWQAAAYgGATQgIATgMAMQgMANgRAGQgRAGgWAAQgVAAgQgGgAgWgjQgJANAAAWQAAAXAJANQAIAMAOAAQAPAAAJgMQAIgNAAgXQAAgWgJgNQgIgMgPAAQgOAAgIAMg");
	this.shape_3.setTransform(721.3,40.8,0.667,0.667);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("ABcBhQgGgBgEgDQgFgEgCgGQgDgFABgKIAAhbQgBgMgGgFQgGgGgLAAQgFABgFACQgHACgCADIAACFIgLACIgQABIgNgBQgGgBgFgDQgEgEgCgGQgDgFAAgKIAAhbQABgMgHgFQgGgGgKAAQgHAAgFACIgHAFIAACGIgMACIgPABIgPgBQgGgBgEgDQgFgEgCgGQgDgGABgJIAAh0QAAgKADgHQAGgGAGgFQAMgJASgGQASgGAUAAQAPAAAOAEQAOAFAKAJQAJgHAQgGQAMgFAUAAQANAAANAEQAPAEAJAIQAKAIAHAOQAFANABAUIAAB5IgMACIgQABg");
	this.shape_4.setTransform(704.1,40.7,0.667,0.667);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgmBmQgSgQAAgiIAAikIALgDQAIgBAIAAQAQAAAJAGQAIAFAAAUIAAAZIAvAAIAEAKQACAGAAAIQAAANgFAHQgHAGgJAAIggAAIAAA5QAAAKAFAEQAGAEALAAIALgBIAKgCQADADADAGQACAFAAAIQAAAPgKAJQgLAJgZAAQgfAAgQgPg");
	this.shape_5.setTransform(684.7,39.6,0.667,0.667);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AggBcQgQgEgMgJQgLgKgIgPQgGgPAAgWIAAhuIAMgCIAQgBIANABQAIACADADQAEADADAHQACAFAAAKIAABSQAAAQAHAGQAHAHANAAQAJAAAFgBIAIgEIAAiGIALgCIAQgBIAPABQAGACAEADQAEACACAIQADAEAAALIAAB0QAAATgPAKQgOAIgQAFQgTAEgTAAQgSAAgRgFg");
	this.shape_6.setTransform(672.6,40.9,0.667,0.667);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AglBdQgSgIgMgMQgNgNgGgSQgHgSAAgYQAAgXAHgSQAHgRAMgOQAMgNASgGQASgIATABQAVgBASAIQARAHAMAMQAMANAIATQAGASAAAWQAAAYgGATQgIATgMAMQgNANgQAGQgRAGgWAAQgVAAgQgGgAgWgjQgJANAAAWQAAAXAJANQAIAMAOAAQAPAAAJgMQAIgNAAgXQAAgWgJgNQgIgMgPAAQgOAAgIAMg");
	this.shape_7.setTransform(658.6,40.8,0.667,0.667);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AggB8QgTgIgMgMQgNgOgHgSQgGgSAAgXQAAgZAHgSQAIgUAMgLQAMgNASgGQARgGATAAQAHAAAHACIALADIAAg+QAEgCAHgBIARgBIAOABQAHABADADQAFAFACAFQACAGAAAKIAAC1QAAASgQALQgLAIgQAFQgPAFgXAAQgXAAgSgGgAgRgFQgKALAAAZQAAAYAJAMQAKAMARAAQAIAAAEgCQAGgCACgDIAAhUQgHgEgKAAQgSAAgLALg");
	this.shape_8.setTransform(639.4,38.7,0.667,0.667);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAsBhQgGgBgEgDQgFgEgCgGQgCgGAAgJIAAhaQAAgMgGgGQgGgFgMgBIgNACIgMAGIAACFIgLACIgQABIgOgBQgHgBgEgDQgFgFgCgFQgCgGAAgJIAAhzQAAgLAEgGQAEgGAHgGQANgKASgFQATgGAVAAQAoAAAXATQAWATAAAiIAAB4IgLACIgQABg");
	this.shape_9.setTransform(625.7,40.7,0.667,0.667);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("ABBCKQgGgCgFgDQgEgEgCgGQgDgGAAgJIAAicIAMgCQAIgBAIAAIAOABQAHABAEADQAEAEACAGQADAGAAAJIAACcIgMADIgQABgAhYCKQgHgCgEgDQgFgFgCgFQgCgGAAgJIAAieQAAgTAGgPQAGgOALgKQAMgJAOgEQAPgEAQAAQAbAAALAHQANAIAAASQAAAIgDAGQgDAGgEADIgNgDQgIgBgJgBQgQABgIAFQgJAGAAAOIAAAMIA6AAIAEAKIACAPQAAAMgGAGQgFAGgIAAIgqAAIAAB6IgLADIgQABgAA0hOQgKgLAAgNQAAgOAKgMQAJgKAPAAQAPAAAJAKQAJALAAAPQAAAOgJAKQgJAKgPAAQgPAAgJgKg");
	this.shape_10.setTransform(610.2,38,0.667,0.667);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgmBdQgRgIgMgMQgNgNgGgSQgHgSAAgYQAAgXAHgSQAHgRAMgOQAMgNARgGQATgIATABQAVgBASAIQARAHAMAMQAMANAHATQAHARAAAXQAAAZgHASQgHATgMAMQgNANgQAGQgRAGgWAAQgUAAgSgGgAgWgjQgJANAAAWQAAAXAJANQAIAMAOAAQAPAAAJgMQAIgOAAgWQAAgWgJgNQgIgMgPAAQgOAAgIAMg");
	this.shape_11.setTransform(589.8,40.8,0.667,0.667);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgnBmQgRgQAAgiIAAikIALgDQAIgBAIAAQAQAAAJAGQAIAFAAAUIAAAZIAvAAIAEAKQACAGAAAIQAAANgGAHQgFAGgKAAIggAAIAAA5QgBAKAHAEQAFAEALAAIAMgBIAKgCQADADACAGQADAGAAAHQAAAPgLAJQgKAJgaAAQgfAAgRgPg");
	this.shape_12.setTransform(578.3,39.6,0.667,0.667);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AggBiQgQgEgGgEQgJgEgFgHQgGgJAAgJQAAgHADgJQAFgFAEgFQANAHALAEQAPAFARAAQAIAAAHgEQAHgDgBgGQAAgFgEgEQgDgCgKgCIgLgCQgfgHgPgPQgQgMAAgaQAAgOAGgMQAFgMALgHQALgIAOgFQAPgEARAAQALAAAOACQAJACALAFQAIAEAFAGQAGAIAAAJQAAAJgDAGQgFAGgDAFIgJgFIgagGIgOgCQgLABgGADQgGACAAAHQAAADADAEQAFADAIABIAMADQAhAIAPAPQAPAPAAAWQAAAegVAQQgUARgnAAQgRAAgLgCg");
	this.shape_13.setTransform(562.6,40.8,0.667,0.667);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("Ag4B4QgJgKgCgPIAXgVQAMgMAJgNQgGgBgHgIQgHgGgIgUIgSgwIgVhRQAGgGAHgDQAJgFAKAAQAMAAAJAGQAIAGAEAPIAbBpIACAAIAeh8QANgIAPAAQANAAAIAHQAIAEAAAPQAAAKgCAPIgHAcIgKAgIgYA9IgNAZQgKAVgIALQgJAKgIAIQgHAHgIACQgGACgKAAQgPABgKgKg");
	this.shape_14.setTransform(549.9,42.9,0.667,0.667);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgiBgQgOgEgMgIQgLgHgGgNQgFgMAAgPQAAgaAOgOQAPgPAfgCIAugGIAAgCQAAgMgJgFQgJgEgQgBQgOABgNADQgOADgKAFQgFgFgDgHQgCgGAAgIQgBgKAFgGQAEgGAKgEQAKgEAPgDQAMgBAOAAQATAAAPAEQAQADAMAKQAMAJAFAMQAHAOgBASIAABVQAAALgEAFQgFAGgIAFQgXAQgrgBQgTAAgPgDgAAAASQgKACgHADQgGADgBAJQAAAHAGAFQAGAFAMAAIANgBQAIgCAEgCIAAgfg");
	this.shape_15.setTransform(536.6,40.8,0.667,0.667);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AggB8QgSgIgNgMQgMgNgHgTQgHgTAAgWQAAgZAHgSQAHgTANgMQAMgMASgHQARgGATAAQAHAAAHACIALADIAAg+QAEgCAIgBQAHgBAJAAIAOABQAGABAFADQAEAEACAGQACAFAAALIAAC1QAAASgQALQgLAIgQAFQgPAFgXAAQgXAAgSgGgAgRgFQgKALAAAZQAAAXAKANQAKAMARAAQAHAAAEgCQAHgDABgCIAAhUQgGgEgLAAQgSAAgLALg");
	this.shape_16.setTransform(523,38.7,0.667,0.667);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAfB7QgJgGgKgOIgjgwIAABGIgMADIgPABIgOgBQgHgCgEgDQgFgFgCgFQgCgGAAgJIAAjeIAMgDQAHgBAIAAIAOABQAHACAEADQAFAEACAFQACAGAAAKIAABlIA9hEQATABALAIQALAJAAAOQAAAGgBAFIgGAJIgsAqIA5A+QgCASgIAKQgIAJgPAAQgMAAgJgGg");
	this.shape_17.setTransform(509.9,38.6,0.667,0.667);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgaBdQgTgHgNgMQgNgMgIgTQgIgVAAgXQAAgaAIgSQAHgSANgMQALgLASgHQARgFAPAAQATgBAQAHQARAGAKALQAMALAFAOQAHAPAAASQAAAMgHAHQgHAIgMABIhYAPQAEALANAHQAMAHAPAAQAOAAANgFQAOgDAHgGQAGADAEAIQAFAHAAAHQAAASgQAJQgLAGgPADQgNABgOAAQgUABgSgHgAgLgvQgIACgDAGQgEAEgCAGIgDAMIA9gKQgBgJgHgHQgGgIgOAAQgIAAgFAEg");
	this.shape_18.setTransform(496.4,40.8,0.667,0.667);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgaBdQgTgGgNgNQgNgMgIgTQgIgUAAgYQAAgbAIgRQAHgSANgMQAMgMARgGQARgFAPAAQAUgBAPAHQAQAGALALQAMALAGAOQAGARAAAQQAAAMgHAHQgHAIgMABIhYAPQADALANAHQANAHAOAAQAPAAANgFQANgDAJgGQAEADAFAIQAEAGAAAIQAAASgPAJQgMAGgOADQgNABgOAAQgUABgSgHgAgMgvQgGADgEAFQgEAEgCAGIgDAMIA9gKQgBgJgGgHQgIgIgNAAQgHAAgHAEg");
	this.shape_19.setTransform(483.2,40.8,0.667,0.667);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AAaBSIgYhdIgZBjQgEAEgJADQgKADgLAAQgPAAgKgFQgLgDgEgJQgEgKgFgTIgUhcIgHgrQAGgGAIgEQAJgEAJAAQANAAAIAGQAIAGACAPIAOBrIACAAIAZhvIAOgHQAHgCAKAAQAMAAAKAEQAIAEADAJIAZBnIACAAIAOh+QAJgFAFgBQAGgCAJAAQAMAAAIAGQAJAGAAAOQAAAHgCAMIgaB4IgGAUQgGAEgKADQgLADgLAAQgeAAgGgQg");
	this.shape_20.setTransform(467.1,40.8,0.667,0.667);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAsBhQgFgBgFgDQgEgEgDgGQgCgFAAgKIAAhaQAAgNgHgFQgFgFgMgBIgMACQgIACgFAEIAACFIgLACIgQABIgOgBQgHgBgEgDQgEgEgCgGQgDgGAAgJIAAhzQAAgLAEgGQAFgHAGgFQAMgJAUgGQASgGAVAAQApAAAWATQAWATAAAiIAAB4IgLACIgQABg");
	this.shape_21.setTransform(445.8,40.7,0.667,0.667);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AglBdQgSgIgMgMQgNgNgGgSQgHgUAAgWQAAgVAHgUQAHgRAMgOQAMgNASgGQASgIATABQAVgBASAIQASAHALAMQAMANAIATQAGASAAAWQAAAYgGATQgIATgMAMQgMANgRAGQgRAGgWAAQgVAAgQgGgAgWgjQgJANAAAWQAAAXAJANQAIAMAOAAQAPAAAJgMQAIgNAAgXQAAgWgJgNQgIgMgPAAQgOAAgIAMg");
	this.shape_22.setTransform(431.8,40.8,0.667,0.667);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("ABcBhQgGgBgFgDQgEgEgCgGQgCgFgBgKIAAhbQAAgMgFgFQgHgGgKAAQgGABgFACQgHACgBADIAACFIgMACIgPABIgOgBQgGgBgEgDQgFgEgCgGQgDgFABgKIAAhbQgBgMgGgFQgHgGgJAAQgIAAgEACIgIAFIAACGIgKACIgRABIgOgBQgGgBgFgDQgEgEgCgGQgDgGAAgJIAAh0QAAgKAFgHQAFgGAGgFQALgJATgGQATgGAUAAQAPAAAOAEQANAFAKAJQAJgHAPgGQANgFAUAAQANAAAOAEQANAEAKAIQALAIAFAOQAHANAAAUIAAB5IgLACIgQABg");
	this.shape_23.setTransform(409.8,40.7,0.667,0.667);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AhGCCQgGgCgFgDQgEgDgCgGQgCgGAAgKIAAi4QAAgKAEgHQAFgHAGgFQALgHARgFQAQgFAVAAQAVAAASAGQAUAHAMAMQANAMAIATQAHATAAAZQAAAZgGARQgGARgMAOQgMANgRAGQgQAGgVAAQgNAAgPgFIAABAIgMADIgQABgAgThNIgJAEIAABUQADACAGACIALABQAkAAAAguQAAgZgJgMQgKgLgQAAQgHAAgFABg");
	this.shape_24.setTransform(392.9,42.9,0.667,0.667);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgmBzQgSgIgNgQQgMgOgHgYQgIgYABgdQgBgcAIgYQAHgXAMgPQAOgQARgIQATgIATAAQAUAAATAIQASAIAMAQQANAPAIAXQAGAYAAAcQAAAdgGAYQgIAYgNAOQgLAPgTAJQgSAIgVAAQgUAAgSgIgAgZg0QgJATAAAhQAAAiAJATQAJASAQAAQAQAAAKgSQAJgTAAgiQAAghgJgTQgKgSgQAAQgQAAgJASg");
	this.shape_25.setTransform(378.3,39.2,0.667,0.667);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgmBzQgSgIgMgQQgOgQgGgWQgIgYABgdQgBgcAIgYQAGgVAOgRQAMgQASgIQATgIATAAQAUAAATAIQAQAIAOAQQANAQAHAWQAHAXAAAdQAAAegHAXQgHAXgNAPQgNAQgRAIQgRAIgWAAQgVAAgRgIgAgZg0QgJATAAAhQAAAiAJATQAIASARAAQARAAAIgSQAKgTAAgiQAAghgKgTQgIgSgRAAQgRAAgIASg");
	this.shape_26.setTransform(363.8,39.2,0.667,0.667);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgYBYQgKgLAAgQQAAgRAKgKQAJgLAPAAQAQAAAKALQAJALAAAQQAAAPgJAMQgKAKgQAAQgPAAgJgKgAgYggQgKgLAAgQQAAgRAKgKQAJgLAPAAQAQAAAKALQAJALAAAQQAAAPgJAMQgKAKgQAAQgPAAgJgKg");
	this.shape_27.setTransform(353.4,40.9,0.667,0.667);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AglB1QgOgCgJgGQgJgEgGgJQgFgHAAgLQAAgLAFgHQAHgJAGgDQALAJALAFQAMAGARAAQAQAAAHgIQAHgIAAgLQAAgLgGgIQgGgHgPAAQgJgBgHADQgIADgHAEQgRgBgLgJQgKgLAAgSIAAgKIAFg6QABgRAJgKQAIgJAQAAIBmAAIAFALQACAGAAAJQAAAPgGAFQgGAHgKAAIhEAAIgCAkIANgEQAIgBAJAAQATAAAOAGQAOAGAIAKQAJAJAEAOQAEAPAAAPQAAARgFANQgFAQgLAKQgKALgRAHQgQAGgYAAQgSAAgMgDg");
	this.shape_28.setTransform(344.3,39.4,0.667,0.667);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgmBdQgSgIgLgMQgNgNgHgSQgGgTAAgXQAAgWAGgTQAHgSANgNQALgNASgGQASgIAUABQAUgBASAIQASAHAMAMQANAPAGARQAHATAAAVQAAAXgHAUQgGASgNANQgNANgRAGQgQAGgWAAQgVAAgRgGgAgXgjQgIAMAAAXQAAAYAJAMQAIAMAOAAQAPAAAIgMQAJgNAAgXQAAgWgJgNQgIgMgPAAQgPAAgIAMg");
	this.shape_29.setTransform(326,40.8,0.667,0.667);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgnBmQgRgQAAgiIAAikIAMgDQAHgBAIAAQARAAAHAGQAJAGgBATIAAAZIAvAAIAFAKIACAOQAAAOgGAGQgFAGgJAAIgiAAIAAA5QAAAKAHAEQAFAEALAAIAMgBIAKgCIAFAJQACAGABAHQAAAPgLAJQgLAJgZAAQgeAAgSgPg");
	this.shape_30.setTransform(314.4,39.6,0.667,0.667);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("ABcBhQgGgBgFgDQgFgFgCgFQgCgGAAgJIAAhbQAAgMgGgFQgGgGgLAAQgGABgFACQgFACgDADIAAADIAACCIgLACIgQABIgNgBQgGgBgFgDQgEgFgCgFQgDgGAAgJIAAhbQAAgNgGgEQgHgGgJAAQgIAAgDACIgIAFIAACGIgMACIgQABIgOgBQgHgBgEgDQgEgEgDgGQgCgFAAgKIAAh0QABgLADgGQAFgFAHgGQAMgJASgGQATgGATAAQAPAAAOAEQAOAFAKAJQAJgHAPgGQANgFAUAAQAMAAAPAEQAMAEALAIQAJAHAIAPQAFANABAUIAAB5IgMACIgQABg");
	this.shape_31.setTransform(294.4,40.7,0.667,0.667);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgiBgQgOgDgMgJQgMgJgFgLQgFgMAAgPQAAgbAOgNQAQgPAegCIAugGIAAgCQAAgMgJgFQgKgEgPgBQgOABgNADQgPADgJAFQgEgEgEgIQgDgGAAgIQAAgKAEgGQAFgGAJgEQALgEAOgDQAMgBAPAAQASAAARAEQAOADANAKQALAIAGANQAHANgBATIAABVQABAKgGAGQgFAHgIAEQgWAQgrgBQgUAAgOgDgAAAASQgLACgGADQgHADAAAJQAAAIAGAEQAFAFANAAIAOgBQAIgCADgCIAAgfg");
	this.shape_32.setTransform(277.4,40.8,0.667,0.667);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgmBzQgSgIgMgQQgNgOgHgYQgIgYABgdQgBgcAIgYQAHgXANgPQAMgQASgIQATgIATAAQAUAAATAIQASAIAMAQQANAPAHAXQAIAYgBAcQABAdgIAYQgHAYgNAOQgLAPgTAJQgRAIgWAAQgVAAgRgIgAgZg0QgJATAAAhQAAAiAJATQAJASAQAAQARAAAJgSQAJgTAAgiQAAghgJgTQgJgSgRAAQgQAAgJASg");
	this.shape_33.setTransform(263.9,39.2,0.667,0.667);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgmBzQgSgIgMgQQgOgQgHgWQgGgYAAgdQAAgcAGgYQAHgVAOgRQAMgQASgIQATgIATAAQAUAAATAIQASAIAMAQQANAPAHAXQAIAYgBAcQABAdgIAYQgHAYgNAOQgMAQgSAIQgRAIgWAAQgUAAgSgIgAgZg0QgJATAAAhQAAAiAJATQAJASAQAAQAQAAAJgSQAKgTAAgiQAAghgKgTQgJgSgQAAQgQAAgJASg");
	this.shape_34.setTransform(249.4,39.2,0.667,0.667);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgYBYQgKgLAAgQQAAgRAKgKQAIgLAQAAQARAAAIALQAKAKAAARQAAAQgKALQgIAKgRAAQgQAAgIgKgAgYggQgKgLAAgQQAAgRAKgKQAIgLAQAAQARAAAIALQAKAKAAARQAAAQgKALQgIAKgRAAQgQAAgIgKg");
	this.shape_35.setTransform(239,40.9,0.667,0.667);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgjB2QgPgEgNgJQgLgKgHgNQgGgMAAgPQAAgWAJgOQAJgOALgGQgJgHgIgNQgHgLAAgVQAAgPAGgNQAGgMALgKQALgJAPgFQARgGAQAAQASAAAOAGQAQAEAKAIQALAJAGAMQAGANAAAPQAAARgGANQgGAMgMAJQANAIAJAPQAJANAAAYQAAAPgGAMQgGAMgMALQgNAJgPAEQgPAFgVABQgUgBgPgFgAgTAeQgGAHAAALQAAAMAHAHQAIAIAKgBQALAAAIgHQAHgHAAgMQAAgLgGgHQgGgHgLgFQgPAEgHAIgAgQhDQgGAGAAAKQAAAKAGAGQAHAGAHAEQAMgDAFgHQAGgGAAgKQAAgKgGgGQgFgHgKABQgLgBgFAHg");
	this.shape_36.setTransform(229.2,39.2,0.667,0.667);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("ABcBhQgGgBgEgDQgFgEgCgGQgCgGAAgJIAAhbQgBgMgFgFQgGgGgLAAQgGABgFACQgFACgDADIAAADIAACCIgMACIgPABIgOgBQgGgBgFgDQgEgEgCgGQgCgGgBgJIAAhbQAAgNgGgEQgHgGgJAAQgHAAgFACIgHAFIAACGIgMACIgQABIgOgBQgGgBgEgDQgFgEgCgGQgCgGAAgJIAAh0QgBgKAFgHQADgFAIgGQALgJAUgGQARgGAUAAQAPAAAOAEQAPAFAJAJQAKgIAPgFQAMgFAUAAQANAAAOAEQAOAEAJAIQAKAIAHAOQAFANAAAUIAAB5IgLACIgQABg");
	this.shape_37.setTransform(207.5,40.7,0.667,0.667);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AglBdQgSgIgMgMQgNgNgGgSQgHgUAAgWQAAgVAHgUQAHgRAMgOQAMgNASgGQASgIATABQAVgBASAIQASAHALAMQANAOAHASQAGASAAAWQAAAYgGATQgHASgNANQgMANgRAGQgRAGgWAAQgVAAgQgGgAgWgjQgJANAAAWQAAAXAJANQAJAMAOAAQAOAAAJgMQAIgNAAgXQAAgXgIgMQgIgMgQAAQgOAAgIAMg");
	this.shape_38.setTransform(190.3,40.8,0.667,0.667);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgpBhQgGgCgEgDQgFgEgCgFQgDgHABgJIAAhyQgBgJAEgHQAEgHAEgEIAPgJIASgHIATgFIAVgCQARAAAKAHQAKAIAAAQQAAAFgBAFIgDAKIgQAAIgeAGIgLAEIAACCIgLADIgPABg");
	this.shape_39.setTransform(178.8,40.7,0.667,0.667);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AguCDQgFgBgFgDQgEgEgDgGQgCgGAAgJIAAifQAAgUAHgOQAFgNAMgKQAKgJAPgEQAPgEAPAAQAbAAAMAHQANAIAAASQAAAIgDAGQgDAFgEAEIgOgDQgIgCgJAAQgPAAgJAGQgIAGAAANIAAANIA6AAIAFAKIABAOQAAAOgGAFQgFAGgJAAIgpAAIAAB6IgLACIgQABg");
	this.shape_40.setTransform(168.8,38.4,0.667,0.667);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("Ag/B4QgJgGgEgJQgEgJAAgMQAAgOAFgJQAFgIAGgFIBAg9IAKgLQAEgGABgEIACgJQAAgMgJgFQgIgHgNAAQgPAAgKAGQgKADgJAHQgGgFgEgHQgEgGAAgKQAAgUARgKQATgKAdAAQATAAAQAGQARAFAKAKQALAKAGAMQAGAOAAAOQAAAqgrAjIguAoIBVAAQADAGABAFQACAGAAAIQAAANgFAHQgGAGgKAAg");
	this.shape_41.setTransform(152,39,0.667,0.667);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("Ag+BwQgTgLAAgSQAAgKAEgIQAFgHAHgEQAKAHAJAEQANAGASAAQASAAAJgHQAIgHAAgLQAAgMgHgFQgHgGgQABIgiAAIgEgLQgCgGAAgHQAAgJACgHQABgGADgEIAiAAQAZgBAAgUQAAgKgIgHQgHgGgRAAQgNAAgNADQgMAFgGAFQgHgGgDgGQgEgFAAgLQAAgTASgJQATgJAfAAQAqAAAUASQAWASAAAgQAAARgJAOQgJANgNAGIAOAHQAGAEAGAIQAFAHADAJQACAKAAAMQAAARgGAMQgHANgMAKQgLAIgRAFQgQAFgTAAQgmAAgSgLg");
	this.shape_42.setTransform(139.4,39.2,0.667,0.667);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAOB0QgDgCgCgGQgDgGAAgJIAAgWIhZAAQgJgEgFgJQgHgJAAgNIACgRQACgJAFgGIBXh1IAOgEIARgCQAIAAAIACQAHACAGAEQAHAFAEAGQADAHAAAKIAABmIAgAAIAFALQABAGAAAJQAAAOgFAGQgHAGgJAAIgRAAIAAAuIgMACIgdABQgGgBgFgDgAgnATIAxAAIAAhIIgBAAg");
	this.shape_43.setTransform(126.3,39.2,0.667,0.667);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AglB1QgOgCgJgGQgJgEgGgJQgFgHAAgLQAAgLAFgHQAGgIAHgEQANAKAJAEQAMAGARAAQAQAAAHgIQAHgHAAgMQAAgLgGgIQgGgHgPAAQgIgBgIADQgIADgHAEQgRgBgKgJQgLgKAAgTIAAgDIAFhBQABgRAJgKQAIgJAQAAIBmAAIAFALQACAGAAAJQAAAPgGAFQgGAHgKAAIhEAAIgCAkIAOgEQAHgBAJAAQATAAAOAGQAOAGAIAKQAJAJAEAOQAEAPAAAPQAAARgFANQgFAQgKAKQgMAMgQAGQgQAGgYAAQgSAAgMgDg");
	this.shape_44.setTransform(112.8,39.4,0.667,0.667);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgtAaQgDgDgCgIQgCgJAAgGQAAgNAGgGQAGgGAKgBIBMAAIAEAMQADAHAAAHQAAAOgGAGQgHAGgJAAg");
	this.shape_45.setTransform(102,40.5,0.667,0.667);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AglB1QgOgDgJgFQgJgEgGgJQgGgIABgKQAAgLAFgHQAGgIAIgEQALAJAKAFQALAGASAAQAQAAAHgIQAIgIAAgLQgBgMgGgHQgGgHgOAAQgJgBgIADIgPAHQgQgBgMgJQgKgKAAgTIAAgDIAFhBQAAgQAKgLQAIgJAPAAIBoAAIADALQADAHAAAIQAAAPgGAFQgHAHgJAAIhEAAIgDAkIAPgEQAGgBALAAQASAAANAGQAQAGAHAKQAJALAEAMQAFAOAAAQQAAAPgGAPQgFAPgLALQgMAMgPAGQgQAGgXAAQgTAAgMgDg");
	this.shape_46.setTransform(91.8,39.4,0.667,0.667);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("Ag/B4QgJgGgEgJQgFgJABgMQAAgOAEgJQAGgIAGgFIBAg9IAKgLIAFgKQACgFAAgEQAAgMgJgFQgIgHgNAAQgPAAgLAGQgKAEgJAGQgFgFgFgHQgDgHAAgJQAAgUARgKQATgKAdAAQASAAARAGQARAFAKAKQALAKAGAMQAGANAAAPQgBAqgqAjIguAoIBVAAIAFALIACAOQAAAOgHAGQgGAGgIAAg");
	this.shape_47.setTransform(79,39,0.667,0.667);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("Ag/B4QgKgHgDgIQgEgJAAgMQAAgNAEgKQAGgIAGgFIBKhIIAGgKIABgJQAAgMgJgFQgIgHgNAAQgPAAgKAGQgLAEgJAGQgFgFgFgHQgDgHAAgJQAAgUASgKQARgKAeAAQASAAARAGQARAFAKAKQALAKAGAMQAGAOAAAOQAAApgrAkIguAoIBVAAIAFALIABAOQABAOgHAGQgGAGgIAAg");
	this.shape_48.setTransform(66.5,39,0.667,0.667);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgtAaIgFgLQgCgGAAgJQAAgNAGgGQAGgGAKgBIBMAAIAFAMQACAGAAAIQAAAOgGAGQgGAGgKAAg");
	this.shape_49.setTransform(55.9,40.5,0.667,0.667);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgmBzQgSgIgNgQQgNgQgGgWQgIgYABgdQgBgcAIgYQAGgVANgRQAOgQARgIQATgIATAAQAUAAATAIQASAIAMAQQANAPAIAXQAGAYAAAcQAAAdgGAYQgIAYgNAOQgLAQgTAIQgRAIgWAAQgUAAgSgIgAgZg0QgJATAAAhQAAAiAJATQAJASAQAAQAQAAAKgSQAJgTAAgiQAAghgJgTQgKgSgQAAQgQAAgJASg");
	this.shape_50.setTransform(44.4,39.2,0.667,0.667);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgmBzQgTgIgMgQQgNgPgGgXQgIgVABggQgBgeAIgWQAGgWANgQQAMgQATgIQASgIAUAAQATAAAUAIQARAIANAQQAOARAGAVQAHAXAAAdQAAAegHAXQgHAWgNAQQgMAQgSAIQgSAIgVAAQgWAAgQgIgAgZg0QgJATAAAhQAAAiAJATQAIASARAAQARAAAIgSQAKgVAAggQAAgfgKgVQgIgSgRAAQgRAAgIASg");
	this.shape_51.setTransform(29.9,39.2,0.667,0.667);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AgkB2QgPgEgMgJQgMgLgGgMQgGgMAAgPQAAgVAIgPQAJgNAMgHQgJgHgIgNQgHgMAAgUQAAgQAHgMQAFgNALgJQAMgKAOgEQARgGAQAAQASAAAPAGQAOAEAMAIQAKAJAGAMQAGANAAAPQAAAPgGAPQgGAMgMAJQAOAJAIAOQAJANAAAYQAAAPgHAMQgFAMgMALQgMAJgQAEQgPAFgVABQgUgBgQgFgAgSAeQgIAIAAAKQAAAMAIAHQAIAIAKgBQAMAAAHgHQAHgHAAgMQAAgKgGgIQgGgHgLgFQgOAEgHAIgAgQhDQgGAFABALQgBAJAGAHQAGAGAIAEQAMgDAGgHQAFgGAAgKQAAgLgFgFQgHgHgJABQgKgBgGAHg");
	this.shape_52.setTransform(15.9,39.2,0.667,0.667);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#000000").s().p("AAPB3QgGgBgFgDQgEgEgBgGQgDgGAAgJIAAiPIgkALQgEgDgHgHQgEgHAAgNQAAgXAagJIAngPIANAAQAQAAAIAKQAKAJgBARIAADIIgLACIgQABg");
	this.shape_53.setTransform(3.8,39.2,0.667,0.667);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#000000").s().p("AgnBmQgRgPAAgkIAAikIAMgCIAPgBQAQAAAJAGQAIAGAAATIAAAZIAvAAQADAFABAFQACAGAAAJQAAAOgGAFQgFAGgKAAIggAAIAAA5QAAALAGADQAGAEAKABIALgBIALgDIAFAKQACAEAAAIQAAAOgKAKQgKAJgaAAQgfAAgRgPg");
	this.shape_54.setTransform(709.5,10.8,0.667,0.667);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#000000").s().p("AghBfQgPgDgMgIQgKgHgHgMQgFgMAAgQQAAgaAOgOQAPgOAfgEIAugFIAAgDQAAgLgJgFQgKgFgQAAQgOAAgMADQgNAEgLAEQgEgEgEgGQgCgIAAgIQgBgJAFgGQAFgHAJgEQAJgEAQgCIAbgBQATAAAPAEQAQAEALAIQAMAJAFAOQAHAMgBATIAABVQABAKgGAHQgGAHgGAEQgXAPgrAAQgRgBgQgEgAAAASQgKABgHAEQgGAEgBAHQAAAIAHAFQAFAFAMgBIANgBQAIgBADgCIAAgfg");
	this.shape_55.setTransform(697.6,12,0.667,0.667);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#000000").s().p("AgaBdQgSgGgOgNQgOgNgHgTQgIgTAAgZQAAgaAIgSQAHgRANgNQAOgMAPgFQAPgGARABQAUAAAPAFQAQAHALAKQALALAHAPQAGARAAAQQAAANgHAGQgHAHgMACIhYAOQAEANAMAGQAMAGAPAAQAPAAANgDQAOgFAIgFQAFADAFAIQADAHAAAIQAAARgPAIQgMAHgOACQgQADgLAAQgVAAgRgHgAgMgwQgFADgFAFQgEAEgCAHIgDAMIA9gLQgBgHgHgIQgHgIgNAAQgHAAgHADg");
	this.shape_56.setTransform(680,12,0.667,0.667);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#000000").s().p("AAtBhQgHgBgEgEQgFgFgCgFQgCgGAAgJIAAhaQgBgLgFgHQgIgFgKAAQgHAAgGACQgGACgGAEIAACEIgLADQgIABgJAAQgIAAgGgBQgGgBgEgEQgFgEgCgGQgCgFAAgKIAAhyQAAgMAEgFQADgHAJgGQALgIATgGQARgGAXAAQAqAAAVATQAWATAAAiIAAB3IgMADQgHABgJAAQgHAAgGgBg");
	this.shape_57.setTransform(666.4,11.9,0.667,0.667);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#000000").s().p("AgKCJQgHAAgEgEQgEgFgCgFQgDgGAAgJIAAidIAMgCIAQgBIANABQAGABAEAEQAFADACAHQACAGAAAJIAACcIgMACQgHABgIAAQgHAAgGgBgAgYhPQgIgJgBgPQABgPAIgJQAJgKAPAAQAPAAAJAKQAKAKAAAOQAAAOgKAKQgIALgQgBQgPABgJgLg");
	this.shape_58.setTransform(656,9.2,0.667,0.667);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#000000").s().p("AgqB3QgOAAgKgJQgJgKAAgRIAAjGIAdgDQAJAAAFABQAHABAEAEQAEADACAHQADAGAAAKIAACXIBRAAQADAEACAHQACAGAAAJQAAAQgGAGQgGAGgKAAg");
	this.shape_59.setTransform(647,10.4,0.667,0.667);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#000000").s().p("AgaBdQgSgGgOgNQgNgNgIgTQgIgUAAgYQAAgZAIgTQAIgTAMgLQAOgMAPgFQAPgGARABQATAAAQAFQAQAHALAKQALALAHAPQAGAPAAASQAAAOgHAFQgHAHgMACIhYAOQAEANAMAGQALAGAQAAQAOAAAOgDQAPgGAHgEQAGAFADAGQAEAHAAAIQAAARgPAIQgMAHgOACQgQADgLAAQgVAAgRgHgAgMgwQgFACgFAGQgEAEgCAHQgCAHAAAFIA8gLQAAgHgIgIQgGgIgOAAQgIAAgGADg");
	this.shape_60.setTransform(628.9,12,0.667,0.667);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#000000").s().p("AgQBcQgUgHgMgNQgNgMgHgTQgIgSAAgWQABgYAHgTQAJgUAMgMQANgMASgGQAQgGAUAAQAaAAAOAKQAOAKAAAPQAAAIgEAGQgDAGgEAFQgHgEgHgCQgKgDgJAAQgJAAgJADQgIADgFAGQgFAGgEAJQgDAJgBALQABAYAMAMQAMAMASAAQALAAAIgDIAOgGQAHAFAEAHQADAIAAAHQAAAPgNAKQgPAIgZAAQgWAAgRgHg");
	this.shape_61.setTransform(616.5,12,0.667,0.667);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#000000").s().p("AgKCJQgHgBgEgDQgEgEgDgGQgCgFAAgKIAAidIAMgCIAPgBIAOABQAGABAEAEQAFADACAHQACAEAAALIAACcIgLACIgQABQgHAAgGgBgAgXhPQgKgJAAgPQAAgPAKgJQAJgKAOAAQAPAAAJAKQAJAJAAAPQAAAPgJAJQgJALgPgBQgOABgJgLg");
	this.shape_62.setTransform(607.2,9.2,0.667,0.667);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#000000").s().p("AgWBeQgKgEgEgIIgIgSIgtiUQAEgEAJgFQAKgEAJAAQANAAAIAGQAIAFAEAQIAaBvIACAAIAOg/IAOhDQAEgDAJgDIAPgCQANAAAJAGQAIAGAAAOIgCASIgRA5IgXA+QgEAMgGAKQgEAFgKACQgKADgMAAQgNAAgLgEg");
	this.shape_63.setTransform(597.2,12,0.667,0.667);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#000000").s().p("AgpBhQgGgBgEgEQgFgFgCgFQgDgGABgJIAAhyQgBgIAEgIQAEgHAEgEQAHgGAIgDIASgHIATgFQAJgCAMAAQARAAAKAIQAKAGAAAQQAAAGgBAFIgEAKIgPABIgeAFIgLAEIAACCIgLADQgHABgIAAQgJAAgGgBg");
	this.shape_64.setTransform(586.2,11.9,0.667,0.667);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#000000").s().p("AgaBdQgSgGgOgNQgNgNgIgTQgIgTAAgZQAAgaAIgSQAIgTAMgLQAOgMAPgFQAPgGARABQAUAAAPAFQAQAHALAKQALAKAHAQQAGAPAAASQAAAOgHAFQgGAHgNACIhYAOQAEANAMAGQALAGAQAAQAPAAANgDQAOgFAIgFQAGADADAIQAEAGAAAJQAAARgPAIQgLAGgPADQgQADgLAAQgUAAgSgHgAgMgwQgFADgFAFQgEAEgCAHIgCAMIA8gLQAAgIgIgHQgGgIgOAAQgHAAgHADg");
	this.shape_65.setTransform(574.3,12,0.667,0.667);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#000000").s().p("AgmB4QgQgEgJgEQgKgFgHgKQgGgHAAgMQAAgKAGgJQAIgIAGgDQAKAIAOAGQAPAGASAAQARAAAGgGQAIgFgBgIQAAgIgFgEQgGgEgKgDIgsgSQgNgGgJgIQgKgIgFgMQgFgLAAgRQAAghAYgUQAXgTAqAAQARAAAMACQANADAJAEQAKAGAGAGQAFAIAAAKQAAAKgEAHQgEAGgGAGQgJgFgNgEQgMgEgRAAQgQAAgHAEQgIAGABAHQAAAGAEADQAGAFAJACIASAGQAhAMATARQASASAAAeQAAAhgZAVQgYAUguAAQgQAAgOgDg");
	this.shape_66.setTransform(561.2,10.4,0.667,0.667);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#000000").s().p("AAsCAQgGgBgEgEQgFgFgCgFQgDgGABgJIAAhVQAAgQgIgGQgHgGgKAAQgIAAgGACQgGACgEACIAACGIgMADQgHABgJAAQgHAAgGgBQgIgBgDgEQgEgDgDgHQgCgFAAgKIAAjeIAMgDQAHgBAIAAQAIAAAGABQAGABAFAEQAEADACAHQADAEAAALIAAAmIAOgFQAIgCAMAAQAkAAAUATQAUATAAAkIAAB1IgMADQgHABgIAAQgIAAgHgBg");
	this.shape_67.setTransform(542.7,9.8,0.667,0.667);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#000000").s().p("AgQBcQgTgHgNgNQgNgNgHgSQgIgSAAgWQAAgZAJgSQAHgUANgMQANgMASgGQARgGATAAQAaAAAOAKQAOAJAAAQQAAAIgDAGQgEAHgEAEQgHgEgIgCQgJgDgJAAQgJAAgIADQgJAEgFAFQgFAGgEAJQgDAJgBALQAAAYANAMQANAMASAAQALAAAHgDIAOgGQAHAFAEAHQADAGAAAJQABAQgOAJQgPAIgZAAQgVAAgSgHg");
	this.shape_68.setTransform(529.8,12,0.667,0.667);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#000000").s().p("AAsBhQgGgBgEgEQgFgEgCgGQgCgGAAgJIAAhaQAAgLgGgHQgHgFgLAAQgHAAgGACQgGACgGAEIAACEIgLADQgIABgIAAQgIAAgGgBQgHgBgEgEQgFgFgCgFQgCgGAAgJIAAhyQAAgLAEgGQAEgHAHgGQANgJASgFQARgGAXAAQApAAAWATQAWATAAAiIAAB3IgLADQgIABgIAAQgIAAgHgBg");
	this.shape_69.setTransform(516.9,11.9,0.667,0.667);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#000000").s().p("AghBfQgPgDgMgIQgLgIgGgLQgGgMAAgQQAAgbAPgNQAPgOAegEIAvgFIAAgDQAAgMgKgEQgJgFgQAAQgOAAgNADQgNAEgKAEQgFgEgDgGQgDgIAAgIQAAgJAEgGQAFgHAKgEQAJgEAPgCIAbgBQAUAAAOAEQARAEAKAIQALAIAHAPQAGAMABATIAABVQgBAJgFAIQgHAHgGAEQgXAPgqAAQgRgBgQgEgAAAASQgLABgGAEQgGAEgBAHQABAIAFAFQAGAFAMgBIANgBQAIgBADgCIAAgfg");
	this.shape_70.setTransform(503.1,12,0.667,0.667);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#000000").s().p("AgpBhQgGgBgEgEQgFgEgCgGQgCgEAAgLIAAhyQAAgJADgHQADgHAGgEQAFgFAJgEIASgHQAJgDAKgCQAKgCALAAQASAAAJAIQAKAGAAAQIgBALIgEAKIgPABIgeAFIgLAEIAACCIgKADIgQABQgIAAgHgBg");
	this.shape_71.setTransform(492.3,11.9,0.667,0.667);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#000000").s().p("AgoB5IgRgDIgQgFQgUgHAAgVIAAiyQAAgKAFgDQADgEAIgDQALgFATgCQARgCAVAAQAtAAAZARQAZAQAAAiQAAASgKANQgIAMgRAGQATAFAMAOQAMAOAAAVQAAAngbARQgaATgxAAgAggBEQAIACAFAAIAPABQANABALgHQAJgGAAgOQAAgNgIgFQgIgFgPAAIgeAAgAgghGIAAAuIAbAAQAOgBAHgGQAHgFAAgMQAAgLgIgGQgHgHgQAAg");
	this.shape_72.setTransform(480,10.4,0.667,0.667);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#000000").s().p("AgpBhQgGgBgFgEQgEgFgCgFQgDgGAAgJIAAhyQAAgJAEgHQADgHAGgEQAGgGAHgDIATgHIATgFQAKgCALAAQARAAALAIQAJAGABAQQgBAGgBAFIgEAKIgPABIgeAFQgGABgFADIAACCIgKADQgIABgJAAQgIAAgGgBg");
	this.shape_73.setTransform(462.8,11.9,0.667,0.667);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#000000").s().p("AggBdQgRgGgLgJQgMgKgGgPQgHgQAAgVIAAhtIALgCIARgBIAOABQAGAAAFAEQAEAFACAFQACAGABAJIAABSQAAARAGAGQAIAHANgBQAIAAAFgBIAIgDIAAiGIAMgCIAPgBIAPABQAGABAEADQAFAEACAGQACAFAAAKIAAB0QAAAUgPAJQgNAJgRAFQgRAEgVAAQgSAAgRgEg");
	this.shape_74.setTransform(450.5,12.2,0.667,0.667);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#000000").s().p("AglBdQgRgHgNgNQgNgNgGgTQgHgTAAgWQAAgVAHgUQAGgSANgNQAMgNASgHQAQgHAVABQAXAAAQAGQARAHAMAOQANAMAHATQAGARAAAXQAAAYgGASQgHATgNANQgMAMgRAHQgTAHgUAAQgTgBgSgGgAgWgjQgJANAAAWQAAAXAJANQAJAMAOAAQAPAAAIgMQAIgNAAgXQAAgXgIgMQgIgNgQAAQgOAAgIANg");
	this.shape_75.setTransform(436.5,12,0.667,0.667);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#000000").s().p("AgmBdQgQgHgOgNQgMgNgHgTQgHgTAAgWQAAgVAHgUQAHgSAMgNQANgNARgHQARgHAVABQAXAAAQAGQAQAHANAOQANAMAGATQAIASgBAWQABAXgIATQgGATgNANQgMAMgRAHQgTAHgUAAQgTgBgTgGgAgXgjQgHAMgBAXQABAYAHAMQAKAMAOAAQAPAAAHgMQAJgNgBgXQABgXgJgMQgHgNgQAAQgOAAgJANg");
	this.shape_76.setTransform(417.6,12,0.667,0.667);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#000000").s().p("AgnBmQgRgPAAgkIAAikIAMgCIAPgBQAQAAAJAGQAIAGAAATIAAAZIAvAAQADAFABAFQACAGAAAJQAAAOgGAFQgFAGgKAAIggAAIAAA5QAAALAGADQAGAEAKABIAMgBIAKgDIAFAKQACAEAAAIQAAAOgKAKQgKAJgaAAQgfAAgRgPg");
	this.shape_77.setTransform(406.1,10.8,0.667,0.667);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#000000").s().p("AgKCAQgGgBgEgEQgFgEgCgGQgCgGgBgJIAAjeIAcgEQAHAAAGABQAHABAEAEQAEADADAHQACAFAAAKIAADeIgMADQgIABgHAAQgHAAgHgBg");
	this.shape_78.setTransform(392.8,9.8,0.667,0.667);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000000").s().p("AgKCAQgGgBgFgEQgEgFgCgFQgDgGAAgJIAAjeIAMgDQAIgBAIAAQAHAAAGABQAGABAFAEQAEADACAHQADAGAAAJIAADeIgMADQgIABgIAAQgHAAgGgBg");
	this.shape_79.setTransform(386.1,9.8,0.667,0.667);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#000000").s().p("AghBfQgPgDgLgIQgLgHgHgMQgFgMgBgQQAAgaAPgOQAOgOAggEIAugFIAAgDQABgLgKgFQgKgFgQAAQgOAAgMADQgNAEgKAEQgEgEgFgGQgCgIAAgIQgBgJAFgGQAFgHAJgEQAJgEAPgCIAbgBQAUAAAOAEQASAEAKAIQAMAJAFAOQAHAMgBATIAABVQABAKgGAHQgGAHgGAEQgXAPgrAAQgRgBgQgEgAAAASQgKABgHAEQgGAEgBAHQAAAIAHAFQAFAFAMgBIANgBQAHgBAEgCIAAgfg");
	this.shape_80.setTransform(375.9,12,0.667,0.667);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#000000").s().p("AgQBcQgTgHgNgNQgNgNgHgSQgHgSgBgWQAAgXAJgUQAHgUANgMQAOgMASgGQAQgGATAAQAbAAANAKQAOAJAAAQQAAAIgDAGIgHALQgIgEgHgCQgJgDgKAAQgJAAgIADQgIADgGAGQgFAHgEAIQgDALAAAJQgBAYANAMQAMAMATAAQALAAAHgDIAOgGQAHAFAEAHQADAGABAJQgBAQgOAJQgOAIgYAAQgWAAgSgHg");
	this.shape_81.setTransform(363.8,12,0.667,0.667);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#000000").s().p("AgiBfQgOgDgMgIQgMgIgFgLQgGgMABgQQAAgbAOgNQAPgOAegEIAvgFIAAgDQAAgMgJgEQgKgFgPAAQgPAAgMADQgOAEgKAEQgFgEgDgGQgDgIAAgIQAAgJAEgGQAGgHAJgEQAJgEAPgCIAbgBQAUAAAPAEQAQAEALAIQAKAIAHAPQAGAMAAATIAABVQAAAJgFAIQgGAHgHAEQgWAPgrAAQgSgBgQgEgAAAASQgLABgGAEQgHAEAAAHQAAAIAGAFQAGAFAMgBIANgBQAHgBAFgCIAAgfg");
	this.shape_82.setTransform(346.4,12,0.667,0.667);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AhGCBQgGAAgFgEQgEgEgCgGQgCgFAAgKIAAi4QAAgLAEgGQADgGAIgGQAKgIASgEQAQgFAVAAQAUAAATAGQARAFAPANQANAMAIATQAHATAAAaQAAAZgGARQgHATgMAMQgLAMgRAHQgRAGgUAAQgPAAgNgFIAABAIgMACQgIACgIAAQgHAAgHgCgAgThNIgKAEIAABUIAKAEIALABQAkAAAAguQAAgZgKgMQgJgMgQAAQgHAAgFACg");
	this.shape_83.setTransform(328.5,14.1,0.667,0.667);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#000000").s().p("AgmBdQgRgHgMgNQgNgNgHgTQgGgSAAgXQAAgXAGgSQAHgSANgNQALgMASgIQARgHAVABQAWAAAQAGQARAHANAOQANAMAGATQAHASAAAWQAAAXgHATQgGASgNAOQgMANgSAGQgSAHgUAAQgUgBgSgGgAgXgjQgIAMAAAXQAAAYAJAMQAIAMAOAAQAQAAAHgMQAJgOAAgWQAAgWgJgNQgIgNgPAAQgPAAgIANg");
	this.shape_84.setTransform(314.2,12,0.667,0.667);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#000000").s().p("AgpBhQgGgBgEgEQgEgDgDgHQgCgFAAgKIAAhyQAAgJADgHQADgHAGgEQAFgFAJgEIASgHQAJgDAKgCQAKgCALAAQASAAAJAIQAKAGAAAQQAAAGgBAFIgEAKIgPABIgeAFIgLAEIAACCIgLADQgHABgJAAQgIAAgGgBg");
	this.shape_85.setTransform(302.7,11.9,0.667,0.667);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#000000").s().p("AggB8QgSgHgNgNQgNgOgGgSQgHgSAAgXQAAgZAHgSQAIgUAMgMQAOgNAQgFQASgGASABIAOABIALADIAAg/IAMgCIAQgBQAIAAAGABQAGABAEADQAEADADAHQACAFAAAKIAAC2QAAASgQALQgIAHgTAGQgRAGgVAAQgWgBgTgGgAgRgEQgKALAAAYQAAAYAJAMQALAMAQAAQAHAAAFgCIAIgFIAAhUQgHgEgKgBQgTABgKAMg");
	this.shape_86.setTransform(290,9.9,0.667,0.667);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#000000").s().p("AAtBhQgHgBgEgEQgEgEgCgGQgDgEAAgLIAAhaQAAgLgGgHQgHgFgKAAQgHAAgHACQgGACgFAEIAACEIgcAEQgHAAgIgBQgFgBgFgEQgFgEgCgGQgCgGAAgJIAAhyQAAgLAEgGQAFgIAHgFQAMgIASgGQARgGAYAAQApAAAVATQAWASAAAjIAAB3IgbAEQgJAAgFgBg");
	this.shape_87.setTransform(271.5,11.9,0.667,0.667);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#000000").s().p("AghBfQgOgDgMgIQgMgHgGgMQgFgMgBgQQAAgaAPgOQAOgOAggEIAugFIAAgDQAAgMgJgEQgKgFgQAAQgOAAgMADQgOAEgJAEQgFgEgDgGQgDgIAAgIQgBgJAFgGQAFgHAJgEQAJgEAPgCIAbgBQAUAAAOAEQARAEALAIQAMAJAFAOQAHAMAAATIAABVQAAAKgGAHQgGAHgGAEQgXAPgrAAQgQgBgRgEgAgBASQgJABgHAEQgGAEAAAHQAAAIAFAFQAGAFAMgBIANgBQAHgBAEgCIAAgfg");
	this.shape_88.setTransform(257.7,12,0.667,0.667);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#000000").s().p("AgRBcQgSgHgNgNQgNgNgHgSQgHgSAAgWQgBgZAJgSQAHgUANgMQAOgMARgGQARgGATAAQAbAAANAKQAOAJAAAQQAAAIgDAGIgIALIgOgGQgJgDgKAAQgJAAgIADQgJAEgFAFQgFAGgEAJQgEAJABALQgBAYANAMQAMAMATAAQAKAAAIgDIAOgGQAHAFAEAHQADAGABAJQgBAQgOAJQgOAIgYAAQgWAAgTgHg");
	this.shape_89.setTransform(245.5,12,0.667,0.667);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#000000").s().p("AgfBdQgSgGgLgJQgMgKgGgPQgHgQAAgVIAAhtIALgCIAQgBIAPABQAGAAAFAEQAEAFACAFQACAGABAJIAABSQgBAQAIAHQAGAHAOgBQAIAAAFgBIAIgDIAAiGIAMgCIAPgBIAPABQAGABAEADQAFAEACAGQACAFAAAKIAAB0QAAAUgPAJQgNAJgRAFQgRAEgVAAQgSAAgQgEg");
	this.shape_90.setTransform(227.9,12.2,0.667,0.667);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#000000").s().p("AglBdQgRgHgNgNQgNgNgHgTQgGgTAAgWQAAgVAGgUQAHgSANgNQAMgNASgHQAQgHAVABQAWAAAQAGQASAHAMAOQANAMAHATQAGASABAWQgBAXgGATQgHATgNANQgMAMgSAHQgSAHgUAAQgUgBgRgGgAgWgjQgIAMAAAXQAAAYAIAMQAIAMAOAAQAPAAAJgMQAHgNABgXQgBgXgHgMQgJgNgPAAQgOAAgIANg");
	this.shape_91.setTransform(213.9,12,0.667,0.667);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#000000").s().p("Ag4B4QgJgJgCgQIAXgVIAVgYQgHgDgGgGQgIgJgIgSIgRgwIgKgjIgLguQAEgFAJgFQAJgEAKAAQAMAAAIAGQAJAFAEAQIAbBpIACAAIAdh8QAOgIAPAAQANAAAIAGQAIAGAAAOQAAAJgCAPIgHAdIgKAgIgMAfIgMAeIgNAZQgHAPgLAQQgJALgIAIQgIAHgHACQgJADgHAAQgPAAgKgKg");
	this.shape_92.setTransform(200.2,14.1,0.667,0.667);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#000000").s().p("AgoAvQAIgXAFgZIAJguIAPgGQAJgDAHAAQALAAAJAGQAIAGAAANQAAAKgCAIQgCAKgEAJIgIATQgFALgEAEQgHAKgGACQgFAFgLAAQgQAAgLgKg");
	this.shape_93.setTransform(185.5,17.4,0.667,0.667);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#000000").s().p("Ag4B4QgJgKgCgPIAsgtQgFgCgIgHQgHgIgIgTIgJgVIgehsQAEgFAJgFQAJgEAKAAQANAAAIAGQAIAGAEAPIAbBpIACAAIAeh8QANgIAPAAQANAAAIAGQAIAGAAAOQAAAJgCAPIgHAdIgKAgIgYA9IgNAZQgHAPgLAQQgJALgIAIQgIAHgHACQgIADgIAAQgOAAgLgKg");
	this.shape_94.setTransform(176.3,14.1,0.667,0.667);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#000000").s().p("AgKCAQgGgBgEgEQgGgEgBgGQgCgFAAgKIAAjeIALgDQAHgBAJAAQAGAAAHABQAGABAEAEQAEADADAHQACAGAAAJIAADeIgLADIgQABQgHAAgGgBg");
	this.shape_95.setTransform(166.4,9.8,0.667,0.667);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#000000").s().p("AgaBdQgSgGgOgNQgNgNgIgTQgIgTAAgZQAAgaAIgSQAIgTAMgLQAOgMAPgFQAPgGARABQAUAAAPAFQAQAHALAKQALAKAHAQQAGAPAAASQAAAOgHAFQgGAHgNACIhYAOQAEANAMAGQALAGAQAAQAPAAANgDQAOgFAIgFQAGADADAIQAEAGAAAJQAAARgPAIQgLAGgPADQgQADgLAAQgUAAgSgHgAgMgwQgFADgFAFQgEAEgCAHIgCAMIA8gLQAAgHgIgIQgGgIgOAAQgHAAgHADg");
	this.shape_96.setTransform(156.5,12,0.667,0.667);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#000000").s().p("AgWBeQgKgEgEgIIgHgSIgKgbIgkh5QAEgEAJgFQAKgEAJAAQAMAAAIAGQAJAFAEAQIAaBvIACAAIAciCQAEgDAKgDIAOgCQANAAAJAGQAIAFAAAPQAAAIgDAKIgHAbIgJAeIgMAgIgKAeIgKAWQgGAFgKACQgJADgMAAQgNAAgLgEg");
	this.shape_97.setTransform(143.3,12,0.667,0.667);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#000000").s().p("AgKCJQgGAAgEgEQgGgEgBgGQgCgFAAgKIAAidIALgCIAQgBIANABQAGABAEAEQAFADACAHQACAGAAAJIAACcIgLACIgQABQgHAAgGgBgAgYhPQgIgJgBgPQABgPAIgJQAJgKAPAAQAQAAAIAKQAKAJAAAPQAAAPgKAJQgIALgQgBQgPABgJgLg");
	this.shape_98.setTransform(133.4,9.2,0.667,0.667);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#000000").s().p("AgnBmQgRgQAAgjIAAikIALgCIAQgBQAQAAAJAGQAHAGABATIAAAZIAvAAIAEAKQACAJAAAGQAAANgGAGQgFAGgKAAIggAAIAAA5QAAALAFADQAHAEAKABIAMgBIAKgDIAFAKQADAGAAAGQAAAOgLAKQgKAJgaAAQgfAAgRgPg");
	this.shape_99.setTransform(125.5,10.8,0.667,0.667);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#000000").s().p("AgiBfQgOgDgMgIQgKgHgHgMQgFgMAAgQQAAgaAOgOQAPgOAfgEIAugFIAAgDQAAgMgJgEQgLgFgOAAQgPAAgMADQgMAEgMAEQgEgEgEgGQgDgJAAgHQAAgJAEgGQAFgGAJgFQAKgEAPgCIAbgBQAVAAAOAEQARAEAKAIQAKAIAIAPQAFAMAAATIAABVQABAJgGAIQgHAGgFAFQgYAPgqAAQgSgBgQgEgAAAASQgMABgFAEQgHAEAAAHQAAAIAGAFQAGAFAMgBIAOgBQAGgBAFgCIAAgfg");
	this.shape_100.setTransform(113.6,12,0.667,0.667);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#000000").s().p("AAtBhQgGgBgFgEQgEgEgDgGQgCgGAAgJIAAhaQAAgLgGgHQgHgFgLAAQgHAAgFACQgHACgGAEIAACEIgLADQgIABgIAAQgIAAgGgBQgGgBgFgEQgEgFgCgFQgDgGAAgJIAAhyQAAgLAFgGQADgHAHgGQANgJATgFQAQgGAXAAQApAAAWATQAWASAAAjIAAB3IgLADIgQABQgIAAgGgBg");
	this.shape_101.setTransform(100.4,11.9,0.667,0.667);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#000000").s().p("AgoBhQgHgBgFgEQgEgFgCgFQgDgGAAgJIAAhyQABgJADgHQAEgIAFgDQAGgGAIgDIASgHIATgFQAKgCALAAQARAAAKAIQALAGgBAQQABAGgCAFIgDAKIgQABIgeAFIgLAEIAACCIgKADQgIABgJAAQgHAAgGgBg");
	this.shape_102.setTransform(88.9,11.9,0.667,0.667);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#000000").s().p("AgaBdQgSgGgOgNQgNgNgIgTQgIgUAAgYQAAgZAIgTQAIgTAMgLQAOgMAPgFQAPgGARABQAUAAAPAFQAQAHALAKQALAKAHAQQAGAPAAASQAAAOgHAFQgGAHgNACIhYAOQAEANAMAGQALAGAQAAQAOAAAOgDQAOgFAIgFQAGADADAIQAEAGAAAJQAAARgPAIQgLAGgPADQgQADgLAAQgUAAgSgHgAgMgwQgFADgFAFQgEAEgCAHQgCAHAAAFIA8gLQAAgHgIgIQgGgIgOAAQgIAAgGADg");
	this.shape_103.setTransform(76.9,12,0.667,0.667);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#000000").s().p("AgnBmQgRgPAAgkIAAikIALgCIAQgBQAQAAAJAGQAHAFAAAUIAAAZIAwAAIAEAKQACAGAAAJQAAANgGAGQgGAGgJAAIghAAIAAA5QAAALAGADQAGAEALABIALgBQAGgBAEgCQADADADAHQACAEAAAIQAAAOgKAKQgKAJgaAAQgfAAgRgPg");
	this.shape_104.setTransform(65.8,10.8,0.667,0.667);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#000000").s().p("AgKCAQgGgBgFgEQgEgEgCgGQgCgFgBgKIAAjeIAMgDQAIgBAHAAQAHAAAHABQAGABAEAEQAFADACAHQADAGgBAJIAADeIgLADIgQABQgHAAgGgBg");
	this.shape_105.setTransform(57.4,9.8,0.667,0.667);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#000000").s().p("AA6B3QgHgCgDgDQgEgCgCgGIgEgLIgHgbIhAAAIgMAwQgEACgGABQgFABgJABQgSgBgJgGQgJgHAAgMIACgKIA8jCQAGgEAMgDQAMgDANgBQARABAOAFQAOAGAEAMIA5DNQgEAEgJAFQgJADgMAAQgIgBgGgBgAgXAQIAsAAIgUhLIgBAAg");
	this.shape_106.setTransform(46.6,10.4,0.667,0.667);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,757.3,51.6);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ag7EaQgVgYAAglQAAglAVgYQAWgYAlAAQAmAAAWAYQAWAXAAAmQAAAmgWAXQgWAYgmAAQglAAgWgYgAgoBWQgQgJgFgXQgEgWgDgpIgFhcIgFhjIgBhUQASgKAVgFQAWgGAUAAQAjAAASARQATARAAAjIAAA9IgDBVQgDApgFAyQgDArgGAkQgDACgHAEQgHADgIABIgdAEQgYAAgQgIg");
	this.shape.setTransform(776.1,88.5,0.667,0.667);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AiDEfQgsgVgBgzQAAgVAJgPQAIgSAKgHQAXAOAgALQAgAKAgAAQAuAAAagRQAbgQAAgkIAAgOQgjAPgwAAQgmAAgjgMQgkgNgYgZQgZgZgQgqQgRgoABg3QAAg4AQgpQARgpAdgbQAcgaApgNQAqgOAtAAQAxAAAnAOQAoANAbAVQARANAJAPQAKAPAAAYIAAE+QAAAugQAlQgSAjgdAWQgdAYgnAKQgoAMgsgBQhNABgsgXgAgoijQgVAZAAAvQAAA0AVAXQAVAXAfAAQAigBAVgQIAAinQgHgEgLgDQgLgEgRAAQgpAAgUAZg");
	this.shape_1.setTransform(751,98.1,0.667,0.667);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("ABpDkQgQgDgJgHQgKgIgGgPQgGgPAAgWIAAjVQAAgcgPgNQgOgOgaAAQgQAAgQAFQgQAEgNAKIAAE6QgLADgPACQgTADgTAAQgTAAgPgDQgOgCgLgIQgKgJgFgOQgGgNAAgYIAAkPQAAgYAKgQQAKgPARgNQAdgXArgNQAsgNA0AAQBgAAA0AtQA0AtAABQIAAEbQgNADgOACQgSADgUAAQgTAAgOgDg");
	this.shape_2.setTransform(719.1,92.9,0.667,0.667);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgZFDQgPgCgKgIQgKgJgGgOQgFgPAAgVIAAlxIAcgFQARgDAUAAQATAAANADQAPADAKAIQALAIAEAOQAGANAAAYIAAFwIgbAFQgTADgTAAQgRAAgPgDgAg4i6QgWgXAAgjQAAgiAWgYQAVgXAjAAQAkAAAVAXQAWAXAAAjQAAAjgWAXQgVAYgkAAQgjAAgVgYg");
	this.shape_3.setTransform(694.6,86.6,0.667,0.667);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("Ag1DeQgYgJgJgVQgJgRgJgZIhIjUIgUhJIgQg/QAMgMAVgKQATgKAYAAQAdAAAUAOQATANAJAkIA/EHIAEAAQAMgwAWhkQAPhDARheQAQgIARgEQASgFARAAQAeAAAUAOQAVAOAAAhQgBAPgGAcIgQA+QgLAlgMAkIg1CSQgPAlgJAQQgMAKgXAGQgVAHgeAAQgfgBgagIg");
	this.shape_4.setTransform(671.1,93.2,0.667,0.667);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgZFDQgOgCgLgIQgLgJgEgOQgGgPAAgVIAAlxIAbgFQATgDASAAQAVAAAMADQAPADAKAIQALAJAFANQAFANAAAYIAAFwIgcAFQgSADgTAAQgRAAgPgDgAg4i6QgWgXAAgjQAAgiAWgYQAUgXAkAAQAkAAAWAXQAVAXAAAjQAAAjgVAXQgWAYgkAAQgkAAgUgYg");
	this.shape_5.setTransform(647.9,86.6,0.667,0.667);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgZEtQgPgDgKgIQgJgHgHgPQgFgPAAgWIAAoNIAbgFQAWgEAPAAQASAAAPADQAPADAKAIQAKAIAGAOQAFAPAAAWIAAIOIgcAFQgSADgSAAQgSAAgPgDg");
	this.shape_6.setTransform(632,88.1,0.667,0.667);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AhhDjQgPgCgKgIQgLgIgFgOQgGgNAAgYIAAkQQABgVAGgPQAIgPAOgLQAMgLAVgLQATgJAXgHQAZgIAWgDQAWgEAcAAQAoAAAYAQQAXARAAAmQAAAOgDALQgDALgGAMIgkABIglAGIghAHQgQAFgKAFIAAE1QgLACgPACQgSAEgUAAQgTAAgOgEg");
	this.shape_7.setTransform(602.1,92.9,0.667,0.667);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AhaDbQgpgRgdgeQgdgfgQgsQgQgpAAg4QAAg3AQgpQAPgqAeghQAfgfAngPQApgQAxgBQAyABApAQQApASAdAeQAdAdAQAtQAQArAAA0QAAA4gQAsQgQAsgdAeQgdAdgpARQgpAPgyAAQgyAAgogQgAg2hUQgUAeAAA2QAAA4AUAdQAUAdAjAAQAkAAASgeQAUgeAAg2QAAg2gUgeQgUgdgjAAQgjAAgTAdg");
	this.shape_8.setTransform(573,93.1,0.667,0.667);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgZFDQgPgCgKgIQgKgJgGgOQgFgNAAgXIAAlxIAcgFQARgDAUAAQATAAANADQAPADAKAIQALAJAFANQAFAPAAAWIAAFwIgcAFQgRADgUAAQgRAAgPgDgAg5i6QgVgYAAgiQAAgiAVgYQAWgXAjAAQAlAAAUAXQAWAYAAAiQAAAjgWAXQgUAYglAAQgjAAgWgYg");
	this.shape_9.setTransform(548.4,86.6,0.667,0.667);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("ABpDkQgQgDgJgHQgKgIgGgPQgGgPAAgWIAAjVQAAgcgOgNQgPgOgaAAQgQAAgQAFQgQAEgNAKIAAE6QgLADgPACQgTADgTAAQgTAAgPgDQgOgDgLgHQgKgKgFgNQgGgPAAgWIAAkPQAAgYAKgQQAKgPARgNQAcgWAsgOQAsgNA0AAQBgAAA0AtQA0AtAABQIAAEbQgOADgNACQgSADgUAAQgSAAgPgDg");
	this.shape_10.setTransform(523.9,92.9,0.667,0.667);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("Ag/DcQgsgQgfgdQgegegUgtQgSguAAg7QAAg8ASgsQATgqAdgdQAdgbAngNQAngOAmAAQAsAAAmAPQAkAOAcAaQAaAZAPAjQAPAlAAApQAAAfgQAPQgRARgcAEIjQAhQAIAeAdAPQAcAPAlABQAkAAAfgKQAegKAUgNQANAJAKARQAJAQAAATQAAAogkAVQgaAPgjAFQghAFgfABQgwAAgrgPgAgdhxQgOAGgKAMQgKANgFANQgFAOAAAOICQgaQgCgQgQgUQgRgSgfAAQgUAAgOAIg");
	this.shape_11.setTransform(492,93.1,0.667,0.667);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AhNDmQgegGgWgLQgWgLgMgRQgMgRAAgYQAAgXAIgOQAJgPAMgKQAXAOAhAMQAgAMApAAQAZgBAPgHQANgJAAgOQAAgNgKgHQgIgGgZgFIgZgGQhKgQgkggQgkghAAg9QAAgjAOgaQANgbAZgSQAagTAhgKQAkgJAngBQAgAAAbAGQAcAFATAKQAUAIANARQAMARAAAVQAAAVgIAPQgFAMgNANQgIgGgMgEQgNgEgQgFIghgGQgRgEgOAAQgaAAgPAHQgQAHAAAPQAAAKAIAGQAJAHAXAFIAaAGQBRAUAjAjQAiAjAAA2QAABFgwAnQgwAoheAAQgmAAgcgGg");
	this.shape_12.setTransform(462.8,93.1,0.667,0.667);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AhaDbQgpgRgdgeQgdgfgQgsQgQgpAAg4QAAg3AQgpQAPgqAeghQAfgfAngPQApgQAxgBQAyABApAQQApASAdAeQAdAdAQAtQAQArAAA0QAAA4gQAsQgQAsgdAeQgdAdgpARQgpAPgyAAQgyAAgogQgAg2hUQgUAeAAA2QAAA4AUAdQAUAdAjAAQAkAAASgeQATgdAAg3QAAg2gTgeQgUgdgjAAQgjAAgTAdg");
	this.shape_13.setTransform(420.7,93.1,0.667,0.667);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AhdDvQgogjAAhTIAAmDIAbgGQASgDATAAQAlAAAVAOQAUAOAAAtIAAA7IBuAAQAGAKAEAPQAFAPAAARQAAAggNAOQgNAOgXABIhMAAIAACHQgBAZAOAJQAOAKAaAAQAOAAANgCQAOgCAJgEQAIAKAFAMQAGALgBATQAAAigXAWQgZAWg9AAQhJAAgpglg");
	this.shape_14.setTransform(393.5,90.3,0.667,0.667);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("ABpDkQgQgDgJgHQgKgIgGgPQgGgPAAgWIAAjVQAAgcgPgNQgOgOgaAAQgQAAgQAFQgQAEgNAKIAAE6QgLADgPACQgTADgTAAQgTAAgPgDQgOgCgLgIQgKgJgFgOQgGgNAAgYIAAkPQAAgYAKgQQAKgPARgNQAdgXArgNQAsgNA0AAQBgAAA0AtQA0AtAABQIAAEbQgNADgOACQgSADgUAAQgTAAgOgDg");
	this.shape_15.setTransform(365,92.9,0.667,0.667);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgZFDQgPgCgKgIQgKgJgGgOQgFgPAAgVIAAlxIAcgFQARgDAUAAQATAAANADQAPADAKAIQALAIAEAOQAGANAAAYIAAFwIgbAFQgTADgTAAQgRAAgPgDgAg4i6QgWgXAAgjQAAgiAWgYQAVgXAjAAQAkAAAVAXQAWAXAAAjQAAAjgWAXQgVAYgkAAQgjAAgVgYg");
	this.shape_16.setTransform(340.6,86.6,0.667,0.667);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AiFEbQgWgXgEglQAWgRAgggQAcgdAWgdQgQgEgQgRQgQgQgUgvIgTgyIgXhAIgXhTQgMgsgOhAQAMgMATgKQAUgKAYAAQAdAAAVAOQASANALAkIBBD4IAEAAIAUhBIAkiYIAPhNQAegRAkAAQAeAAAUAOQATAOAAAhQAAAZgGAgQgHAkgJAgQgGAZgQAyIgcBLQgOAlgQAiQgPAfgPAcQgZAvgTAZQgUAcgSAQQgTAQgSAHQgTAFgUAAQgkAAgWgWg");
	this.shape_17.setTransform(305.6,98.2,0.667,0.667);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgZEtQgPgDgKgIQgJgHgHgPQgFgPAAgWIAAoNIAbgFQAWgEAPAAQASAAAPADQAPADAKAIQAKAIAGAOQAFAPAAAWIAAIOIgcAFQgSADgSAAQgSAAgPgDg");
	this.shape_18.setTransform(282.2,88.1,0.667,0.667);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AhtElQgmgNgdgWQglgbAAgtIAAnjQAIgDATgDQAWgDAQAAQASAAAPADQAQADAKAIQAKAIAFAOQAFANAAAYIAABZQAWgKATgDQARgEAXAAQApAAAlAQQAlAPAbAeQAdAeAPArQAQApAAA6QAAA8gQArQgRAtgdAcQgeAdgrAPQgqAPg0AAQg4AAgmgOgAgrgkQgKACgRAIIAADFQAKAHANAEQAOAEASAAQAnAAAVgdQAVgcAAg5QAAg5gVgbQgWgcglAAQgQAAgNAEg");
	this.shape_19.setTransform(258.3,88.3,0.667,0.667);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AhQDiQgkgKgagRQgagTgOgcQgOgbAAgmQAAg+AjgiQAjghBJgIIBugNIAAgGQAAgagWgMQgWgMgnAAQggAAgfAIQgfAHgYALQgLgIgIgRQgIgQAAgTQAAgYALgOQALgOAWgJQAagKAggFQAigFAdAAQAsAAAnALQAmAJAaAVQAbAVAOAfQAPAgAAAqIAADKQAAAXgNAQQgLANgSANQg3AihkABQgsgBgkgIgAgDArQgYACgPAJQgPAJAAATQAAASANALQANALAfAAQAPAAARgDQAQgDAJgFIAAhJg");
	this.shape_20.setTransform(224.9,93.1,0.667,0.667);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AhcDvQgpgjAAhTIAAmDIAagGQASgDATAAQAmAAAVAOQATAOAAAtIAAA7IBvAAQAGAKAEAPQAFAPAAARQAAAggNAOQgNAOgWABIhOAAIAACHQAAAZAPAJQANAKAaAAQAOAAANgCQAMgCALgEQAIAKAFAMQAGALAAATQAAAigYAWQgZAWg9AAQhJAAgoglg");
	this.shape_21.setTransform(199.6,90.3,0.667,0.667);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AhhDjQgQgCgJgIQgKgIgGgOQgGgPAAgWIAAkQQAAgUAIgQQAGgOAOgMQAMgLAWgLQAVgKAWgGQAZgIAVgDQAWgEAbAAQAqAAAXAQQAYARAAAmQAAAOgEALQgCALgGAMIglABIgkAGIgiAHQgSAFgIAFIAAE1QgNADgNABQgSAEgUAAQgSAAgPgEg");
	this.shape_22.setTransform(176.9,92.9,0.667,0.667);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AhaDbQgpgRgdgeQgdgfgQgsQgQgpAAg4QAAg3AQgpQAPgqAeghQAfgfAngPQApgQAxgBQAyABApAQQApASAdAeQAdAdAQAtQAQArAAA0QAAA4gQAsQgQAsgdAeQgdAdgpARQgpAPgyAAQgyAAgogQgAg2hUQgUAeAAA2QAAA4AUAdQAUAdAjAAQAkAAASgeQATgdAAg3QAAg2gTgeQgUgdgjAAQgjAAgTAdg");
	this.shape_23.setTransform(147.8,93.1,0.667,0.667);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AhsE1QgPgCgKgJQgLgJgFgNQgFgPAAgWIAAl3QAAguAPghQAPgiAZgVQAagVAigKQAhgKAnAAQA+AAAfASQAdASAAAqQAAASgHAPQgHANgJAJIghgIQgRgDgXAAQglAAgUANQgUANAAAhIAAAdICKAAQAGAKAEAPQAFAPAAASQAAAggNANQgNAOgWAAIhhAAIAAEgQgMADgPACQgSADgTAAQgTAAgPgDg");
	this.shape_24.setTransform(120.3,87.5,0.667,0.667);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("ADZDkQgPgCgKgIQgLgKgFgNQgFgNAAgYIAAjYQAAgbgPgMQgPgNgYAAQgMABgNAFQgPAHgGAGIABAGIAAE0IgbAFQgSADgTAAQgSAAgPgDQgOgCgLgIQgKgJgFgOQgGgNAAgYIAAjYQAAgbgQgMQgQgNgVAAQgOABgNAFIgSAJIAAE+QgOADgNACQgSADgUAAQgSAAgPgDQgQgDgJgHQgKgIgGgPQgGgPAAgWIAAkRQAAgYAKgPQAKgOARgNQAegWAqgOQArgNAuAAQAjAAAhAKQAiALAXAVQAagTAggLQAfgMAuAAQAgAAAfAJQAfAJAYATQAYAUAOAhQAPAfAAAvIAAEdQgMADgPACQgSADgUAAQgSAAgPgDg");
	this.shape_25.setTransform(83,92.9,0.667,0.667);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AhaDbQgpgRgdgeQgdgfgQgsQgQgpAAg4QAAg3AQgpQAPgqAeghQAfgfAngPQApgQAxgBQAyABApAQQApASAdAeQAdAdAQAtQAQArAAA0QAAA4gQAsQgQAsgdAeQgdAdgpARQgpAPgyAAQgyAAgogQgAg2hUQgUAeAAA2QAAA4AUAdQAUAdAjAAQAkAAASgeQATgdAAg3QAAg2gTgeQgUgdgjAAQgjAAgTAdg");
	this.shape_26.setTransform(42.5,93.1,0.667,0.667);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgoDZQgrgQgfgfQgegdgSgsQgRgqAAg0QAAg7ASgtQATgtAfgdQAfgeApgOQApgOAtAAQA9AAAhAXQAhAYAAAlQAAARgHAPQgHAPgLALQgNgHgWgHQgVgHgXAAQgVAAgTAIQgTAGgNAPQgPAOgIAVQgIAUAAAcQAAA5AeAbQAcAcAsAAQAaAAASgGQAVgHAMgHQARANAJAPQAIAQAAAUQAAAmghAUQghAUg6AAQg0AAgsgRg");
	this.shape_27.setTransform(12,93.1,0.667,0.667);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#CA0303").s().p("AhtEUQglAAgVgWQgVgXAAgnIAAl/QAAgnAVgXQAVgWAlAAIEXAAQAGALAEAPQAFAPAAAUQAAAhgOAPQgOAPgXAAIiyAAIAABUIC+AAQAGALAFAQQAEAPAAATQAAAggNAPQgOAPgXAAIibAAIAABfIDZAAQAHALAEAPQAFATAAAQQAAAigOAQQgOAPgXgBg");
	this.shape_28.setTransform(678.7,21.7,0.667,0.667);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#CA0303").s().p("AhcEcQgfgHgbgNQgagPgNgSQgOgUAAgZQAAgaAOgTQAPgTARgJQAYATAiAPQAjAOAoAAQApABAQgOQARgOAAgSQAAgTgNgJQgOgKgXgJIgkgMQgdgLgmgQQgfgOgWgUQgWgTgNgdQgMgdAAgmQAAhNA3gvQA5guBiAAQAjAAAiAGQAgAGAVALQAXALANASQAMARAAAYQAAAXgKARQgKARgPAMQgSgNgggJQgegKgnAAQgkAAgSAMQgTALABARQgBANALAJQANAKAVAGIAsAQQBPAbArApQArAqAABJQAABNg4AvQg5AwhuAAQgoAAghgGg");
	this.shape_29.setTransform(647.1,21.6,0.667,0.667);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#CA0303").s().p("ACIEYQgPgEgJgGQgIgHgFgNQgGgJgEgSIgQg+IiYAAIgbBwQgNAFgNADQgOADgSAAQgqAAgWgQQgUgQAAgcQAAgNAEgMIAXhbIB2luQAPgKAcgHQAegIAeAAQAqAAAgANQAgANAKAcQAQAxAQA9IBlF3QgLANgUAHQgWAIgaAAQgTAAgPgEgAgcg4QgQAygKAsIBnAAIguizIgEAAg");
	this.shape_30.setTransform(613.7,21.7,0.667,0.667);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#CA0303").s().p("AhtEUQgkAAgVgWQgWgXAAgnIAAl/QAAgnAWgXQAVgWAkAAIEXAAQAHALAEAPQAFASAAARQAAAhgOAPQgPAPgWAAIiyAAIAABUIC9AAQAGAKAFARQAFAPAAATQAAAggOAPQgNAPgXAAIibAAIAABfIDZAAQAGALAEAPQAFARAAASQAAAjgOAPQgOAPgXgBg");
	this.shape_31.setTransform(581.1,21.7,0.667,0.667);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AhMEjQgtgQgdggQgegfgQgrQgPgrAAg2QgBg8ARgrQASgtAegcQAegdAogOQAogOAuAAQARAAAQADQARAEAKAEIAAiTQAIgDATgDQASgDATAAQAWAAAMADQAPACAKAJQALAHAEAOQAGAOAAAXIAAGtQAAArgmAaQgZASgmAMQgmANg0AAQg4AAgqgQgAgpgMQgZAaABA6QAAA5AWAcQAXAcArABQAPAAAMgGQALgDAIgIIAAjHQgRgLgYABQgsgBgZAdg");
	this.shape_32.setTransform(536.3,20.5,0.667,0.667);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("ABpDkQgQgCgJgJQgKgHgGgPQgGgPAAgVIAAjWQAAgcgPgNQgOgNgaAAQgQgBgQAFQgRAGgMAIIAAE6QgLADgPACQgTADgTAAQgTAAgPgDQgOgCgLgJQgKgHgFgPQgGgNAAgXIAAkQQAAgYAKgQQAKgQARgMQAdgWArgNQAsgOA0AAQBgAAA0AtQA0AtAABPIAAEcQgNAEgOABQgSADgUAAQgTAAgOgDg");
	this.shape_33.setTransform(503.9,25.1,0.667,0.667);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AhQDiQgkgKgagSQgZgRgPgdQgOgbAAgmQAAg/AjggQAigiBKgIIBugNIAAgGQAAgbgWgLQgWgLgnAAQghgBgeAIQgeAIgZAKQgMgJgHgQQgHgRAAgRQAAgYAKgOQALgOAWgLQAZgKAhgEQAhgEAeAAQAsgBAnALQAmAJAaAVQAbAUAOAfQAPAfAAArIAADLQAAAXgMAPQgNAPgRALQg2AkhlgBQgsABgkgJgAgCArQgZACgOAJQgQAJAAASQAAATAOALQAMALAfAAQAPAAARgDQARgDAJgGIAAhIg");
	this.shape_34.setTransform(471.3,25.3,0.667,0.667);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AinExQgPgDgKgIQgKgIgFgOQgFgNAAgYIAAmyQAAgZAKgPQAKgQAQgMQAcgTAmgKQAmgLAxAAQAzAAAqAOQAsAOAgAdQAfAdASAsQASAsAAA9QAAA4gPAsQgPArgcAfQgcAdgoAPQgpAOguAAQgkAAgggMIAACXQgIADgTADQgWADgQAAQgTAAgPgDgAgvi2QgOAEgHAFIAADHQAJAFAMAEQAMADAOAAQBWAAAAhuQAAg7gWgbQgVgdgoAAQgQAAgNAFg");
	this.shape_35.setTransform(429.4,30.2,0.667,0.667);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AhQDiQgkgKgagSQgagSgOgcQgOgdAAgkQAAg/AjggQAigiBJgIIBvgNIAAgGQAAgagWgMQgWgLgnAAQgggBgfAIQgdAHgaALQgLgIgIgRQgIgRAAgRQAAgYALgOQAMgPAVgKQAagKAggEQAigEAdAAQAsgBAnALQAmAJAaAVQAaAUAQAfQAOAgAAAqIAADLQAAAXgMAPQgMAOgSAMQg3AkhkgBQgsABgkgJgAgCArQgZACgOAJQgQAJABASQgBATANALQANALAfAAQAOAAASgDQARgDAJgGIAAhIg");
	this.shape_36.setTransform(396.2,25.3,0.667,0.667);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("Ag/DcQgrgPgfgeQgggegTguQgSgtAAg8QAAg7ASgrQATgrAdgcQAdgcAngOQAngNAmABQAsAAAmAOQAkAOAcAaQAaAZAPAkQAPAjAAAqQAAAfgQAPQgRAQgcAFIjQAiQAJAdAcAQQAdAPAkgBQAlAAAegJQAegKAUgMQANAIAKARQAJAQAAASQAAAqgkATQgaAPgjAGQgfAGgggBQgwAAgsgOgAgdhyQgOAHgKAMQgJALgGAOQgFAPAAAOICQgaQgCgSgQgSQgQgSggAAQgTAAgPAHg");
	this.shape_37.setTransform(366,25.3,0.667,0.667);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgZEtQgPgCgKgJQgKgJgGgOQgFgNAAgXIAAoNIAcgGQASgCASAAQAVgBAMADQAPADAKAIQALAJAEANQAGAPAAAWIAAINIgbAGQgTACgSAAQgSAAgPgCg");
	this.shape_38.setTransform(342.5,20.2,0.667,0.667);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("Ag/DcQgrgPgfgeQghgegSguQgSgsAAg9QAAg8ASgqQASgrAegcQAdgcAngOQAngNAmABQAsAAAmAOQAlAPAbAZQAbAZAOAkQAPAkAAApQAAAfgQAPQgRAQgcAFIjQAiQAJAdAcAQQAdAPAlgBQAkAAAegJQAegKAUgMQANAIAKARQAJARAAARQABAqglATQgaAPgjAGQgfAGgggBQgwAAgsgOgAgdhyQgPAHgJAMQgJALgFAOQgEANgBAQICQgaQgDgSgQgSQgQgSggAAQgTAAgPAHg");
	this.shape_39.setTransform(307.8,25.3,0.667,0.667);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("ABpEtQgQgDgJgIQgKgHgGgQQgGgPAAgVIAAjJQAAglgRgPQgSgPgYAAQgQAAgQAFQgQAFgJAFIAAE9QgLAEgPACQgTACgTAAQgTAAgPgCQgOgCgLgJQgKgJgFgOQgGgNAAgXIAAoNIAcgGQASgCATAAQAVgBAMADQAPADAKAIQALAJAFANQAFANAAAYIAABZIAigKQAWgHAbABQBUAAAvAtQAvAtAABYIAAESQgOAEgNACQgSACgUAAQgSAAgPgCg");
	this.shape_40.setTransform(275.7,20.2,0.667,0.667);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AhcDwQgpglAAhRIAAmEIAbgGQASgDASAAQAnAAAUAOQAUAOgBAuIAAA5IBvAAQAGALAFAOQAEAPAAATQAAAggNAOQgNANgWAAIhOAAIAACJQABAXAOAKQANAKAaAAQAPAAALgCQAOgDAKgDQAIAKAFAMQAGANAAARQAAAigZAWQgYAWg8AAQhKAAgogkg");
	this.shape_41.setTransform(248.5,22.5,0.667,0.667);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("Ag/DcQgrgPgggeQgggfgSgtQgSgtAAg8QAAg7ASgrQASgrAegcQAdgcAngOQAngNAmABQAsAAAmAOQAkAOAcAaQAbAaAOAjQAPAiAAArQAAAfgQAPQgQAQgdAFIjRAiQAKAeAdAPQAbAPAmgBQAjAAAegJQAfgJAUgNQAOAJAJAQQAJAQAAASQAAApgjAUQgcAPgiAGQggAGgfgBQgxAAgrgOgAgdhyQgPAHgJAMQgKALgEAOQgFAPgBAOICQgaQgCgRgQgTQgRgSgfAAQgTAAgPAHg");
	this.shape_42.setTransform(209.7,25.3,0.667,0.667);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("ABJEiQgVgOgZgiIhShxIAACmIgcAFQgSADgTAAQgSAAgQgDQgOgCgLgJQgKgIgFgOQgFgPAAgVIAAoNQAIgDATgDQASgDATAAQAVAAANADQAPACAKAJQAKAHAFAOQAFAOABAXIAADvICQifQAsAAAbAVQAbAVAAAgQAAAMgEAMQgEALgJANQgIAKgPAPIhSBLICHCRQgDAqgTAXQgUAXgkAAQgbAAgWgOg");
	this.shape_43.setTransform(179.2,20.3,0.667,0.667);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AhQDiQgkgKgagSQgZgRgPgdQgOgbAAgmQAAg/AjggQAigiBKgIIBugNIAAgGQAAgbgWgLQgWgLgnAAQghgBgeAIQgeAIgZAKQgMgJgHgQQgHgRAAgRQAAgYAKgOQALgOAWgLQAZgKAhgEQAhgEAeAAQAsgBAnALQAmAJAaAVQAbAUAOAfQAPAfAAArIAADLQAAAXgMAPQgNAPgRALQg3AkhkgBQgsABgkgJgAgCArQgZACgOAJQgQAJAAASQAAASANAMQANALAfAAQAPAAARgDQARgDAJgGIAAhIg");
	this.shape_44.setTransform(146.8,25.3,0.667,0.667);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgeEUQgOgEgLgIQgLgIgEgOQgGgQAAgWIAAlgIh/AAQgFgJgGgSQgFgQAAgVQAAgiAPgQQAPgQAYAAIFwAAQAHAMAEAQQAGARAAATQAAAjgPAQQgPAPgYAAIheAAIAAGiQgGADgXADQgRACgXABQgSAAgPgDg");
	this.shape_45.setTransform(116.3,21.7,0.667,0.667);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,781.5,118.8);


(lib.ClipGroup_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	mask.setTransform(960,540);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKAUIgdgfQgEgEAEgFQABAAAAAAQABgBAAAAQABAAAAAAQABAAABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAIAeAgQAEAEgEAEQgDACgCAAQgCAAgDgCg");
	this.shape.setTransform(1245.4,192.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AALANIgbgOQgGgDADgGQABgCADgBIAFABIAbAOQAGADgDAGQgCADgDAAIgEgBg");
	this.shape_1.setTransform(1247.9,191.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAOBBIgjgOQgSgGAHgRIAghTQAFgOAPAFQAPAGgGAOIgdBMIAXAJQAQAFgFAMQgCAGgGABIgFABIgHgBg");
	this.shape_2.setTransform(1246.2,182.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgDBMIgigTQgPgJAJgPIA9hoQADgGAGgBQAGgCAGADQAOAIgIANIg5BhIAVANQAPAIgHALQgEAHgGAAQgFAAgFgEg");
	this.shape_3.setTransform(1239.7,181.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLA2QgcgHgLgUQgJgRAFgUQAGgZATgMQASgMAZAHQAYAFAMASQAKARgFASQgCAHgDACQgDACgIgCIhBgPQgDALAGAIQAFAJANADQALADAKgFQALgFAEABQAFACADAEQACAEgBAEQgCAMgTADIgOACQgHAAgJgCgAgWgQIAzAMQABgKgFgIQgGgIgJgCIgIgBQgOAAgKARg");
	this.shape_4.setTransform(1229.7,178.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAfBPQgKAAgEgFQgEgEgBgJIgOhYIAAAAIgeBVQgDAIgEADQgFAEgJgBQgJAAgEgEQgFgEgBgJIgUhuIgBgKQABgHAGgDQAEgEAHABQANAAACAOIALBgIABAAIAfhdQACgHAEgCQAEgDAIABQAKABAEAFQACADACAIIAOBeIABAAIAchdQAEgNAMABQAHABAEAEQAFAEgBAHQAAADgCAGIgnBqQgDAJgEADQgEACgIAAIgCAAg");
	this.shape_5.setTransform(1215,173.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjAsQgPgMgDgWQgEgYANgSQANgSAagDQAXgDASAMQAQAMADATQABAHgCADQgDADgHAAIhDAJQACAMAJAGQAIAHAMgCQAMgCAIgIQAIgJAEAAQAGgBAEADQAEADAAAEQACAMgQAKQgNAIgQACIgLABQgVAAgOgLgAgBghQgXADgBAYIAzgIQgCgJgIgGQgHgFgIAAIgCABg");
	this.shape_6.setTransform(1194.3,175.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgJBOQgQgDgDgKQgCgFADgEQACgFAFgBQAGgBAKAEQAKAFAIgCQANgEAEgJQAEgJgFgQIgCgGIgBAAQgCAHgGAGQgHAGgIADQgWAGgQgJQgQgKgGgVQgIgZAJgSQAIgRAUgFQAWgHAMAPIABAAIgBgEQgFgNAOgEQANgDAEANIAZBQQAHAYgKARQgKAQgXAHQgMADgKAAIgJgBgAgNguQgYAHAJAfQAEAKAHAGQAJAHALgEQAWgGgIgbQgHgYgQAAIgHAAg");
	this.shape_7.setTransform(1182.4,179.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AguBKIgEgNIgUh1QgCgKALgHIAHgEQAMgHAKAJIBcBLQAHAFACADQADAGgCAFQgCAGgFADQgKAGgIgGIgUgQIguAaIAFAZQABAKgKAFQgFADgEAAQgHAAgFgHgAgngsIAMA7IAigSIgugpg");
	this.shape_8.setTransform(1170.2,182.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAFCIQghgBgbgNQgbgNgXgcQgFgFAFgFIAZgZQACgDAEAAQADABACADQAfApAvABQAWAAANgIQANgHABgOQAAgMgJgIQgJgIgWgHIgsgNQgggJgSgTQgSgUABgZQABgiAcgUQAcgVArABQA7ABAiAmQAFAFgFAGIgYAXQgCAEgEAAQgDAAgDgEQgagcgggBQgWAAgOAIQgOAIAAAOQAAAWAqAMIAvAOQAhAJAPARQAQATgBAdQAAAigdAVQgbAUgrAAIgEAAg");
	this.shape_9.setTransform(1192.7,202.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgDCIQg6gBglgnQglgoAAg5QABg7AngnQAnglA6ABQA9ABAoApQAFAFgFAGIgXAYQgFAFgGgFQgQgQgPgHQgQgHgVgBQgkAAgYAZQgXAYgBAoQgBAmAXAZQAXAaAkAAQAfABAXgQQAWgPAIgdIhSgCQgHABAAgIIAAgeQAAgJAIAAIB/ADQAIAAAAAIIAAAKQgBA6goAmQgmAlg5AAIgDAAg");
	this.shape_10.setTransform(1218.6,202.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#EE1F3C").s().p("AnCA2Qg5g4gbg/Qgcg/AChDQACg6AZg3QAZg1AugrQAtgrA4gWQA5gXA9AAIAAAAQCGAABwBrQA5gzBAgaQBAgZBCABQA+ACA3AYQA5AZArArQAsAsAXA3QAYA3gBA7QAABDgfA/QgeA+g6A3InFGpg");
	this.shape_11.setTransform(1206.6,196.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AhXB/QgPgFgLgKQgKgJgGgNQgGgMAAgNQAAgdARgSQAQgSAngOQgKgQgDgQQgCgIAAgIQAAgdATgTQATgUAjAAQAfAAAQAOQARAPAAAVQAAAYgVAQQgLAKgcAMIAwBJQAKgMADgGQAFgJAAgKQAAgKgMgFQgHgCgMAAIAAgQIBeAAIAAARQgSABgJAGQgHAFgJAPIgSAgIgIAKQAMAOAIAFQAHAFAIAAQALAAAGgIQAGgHADgPIAQAEQgFAbgPARQgOARgcAAQgNAAgOgFQgOgEgPgNQgPALgQAGQgTAGgXAAQgRAAgPgEgAg9ADQgDACgHAKQgFAIAAANQAAAVAPAXQAQAXAaAAQAJAAAHgDIAIgFQgNgQgVggQgSgbgEgJQgEgJgEAAIgCABgAgYhpQgHAJAAAOQAAAJAGANIAPAaQANgFAHgIQAMgLAAgVQAAgKgEgIQgHgQgRAAQgLABgHAHg");
	this.shape_12.setTransform(954.2,164.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("ABXCDIgSgjQgTASgMAGQgUALgcgBQg7AAgjgnQgegiAAgyQAAhJAygnQAmgZAsAAQAXAAAUAHQAMAFANAIIAUgSIAPAAIADBjIgRABQgNgmgNgRQgWgegjAAQgnABgPAiQgQAlAAAuQAAA2AQAbQAPAcAgAAQAgAAAMgaQAGgOABgbQAAgLgCgDQgDgEgIgBIgXAAIAAgTIB7AAIAAATQgUABgFACQgGACAAAKIAABYg");
	this.shape_13.setTransform(916.2,164.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("ABTB/IijjDIAACFQAAAZANAKQAHAFATAAIAAATIhkAAIAAgTQAZAAAHgKQAGgLAAgfIAAiOIgGgHQgFgFgHgDIgHgDIgMgCIAAgRIBYAAICGCfIAAhpQAAgXgNgIQgIgFgSgBIAAgRIBjAAIAAARQgXACgHALQgHAKAAAbIAAC6g");
	this.shape_14.setTransform(889.2,164.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AhCB+IAAgTIAWAAQAKAAABgGQADgEAAgJIAAixQAAgKgEgEQgDgDgHAAIgWAAIAAgTICGAAIAAATIgUAAQgJABgEADQgEADAAALIAAC0QAAAKAEACQAEACAJABIAUAAIAAATg");
	this.shape_15.setTransform(866.8,164.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgbB+QgTgGgOgMIgWAVIgPAAIgDhiIARgBQANAiAXAZQAYAYAiAAQAUAAAOgLQAPgKAAgSQAAgUgOgJQgIgGgUgDIgYgFQglgHgTgMQgmgWAAgqQAAgjAZgWQAagVAoAAQAUAAASAHQALAEAMAIIATgRIAPAAIAEBbIgRABQgPgogXgSQgZgSgXAAQgUAAgNAKQgOAJAAARQAAASAPAJQAJAFAPADIAdAHQAqAJAUANQAfAUAAAqQAAAjgZAXQgZAXgoAAQgVAAgRgFg");
	this.shape_16.setTransform(848.4,164.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AhAB0QgogUAAg0IAAiIIgBgIQAAgEgDgDQgEgCgLAAIgRgBIAAgSICFAAIAAASQgYABgFACQgGADAAAMIAAB7QAAAhAIAOQANAYAnAAQApgBAOgdQAHgPABgdIAAhkQgBgUgJgJQgJgHgVgCIAAgSIBjAAIAAASQgTADgGAFQgLAIgBAXIgBBvQAAA0gfATQggASgnAAQgnAAgZgNg");
	this.shape_17.setTransform(824.3,165);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AhfBaQgjgnAAgzQAAg4AngmQAmgkA1AAQA9AAAmArQAgAmAAAxQAAAyghAmQglArg+AAQg5AAglgpgAg1hCQgIAYAAAtQAAArANAiQAOAiAlAAQAfAAAOgdQAOgdAAg4QAAgvgNghQgOgggiAAQgoAAgOAug");
	this.shape_18.setTransform(797.6,164.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAMB+IAAgTIANAAQAQAAACgFQAEgDAAgOIAAhNIhdAAIAABRQAAAMAFACQADAEALAAIARAAIAAATIiFAAIAAgSIAUgBQALgBACgEQADgDgBgLIABixQAAgMgEgCQgFgCgbgBIAAgTICFAAIAAATIgVAAQgJAAgDAFQgCADgBAJIAABLIBdAAIAAhJQAAgLgDgDQgDgEgIgBIgVAAIAAgTICEAAIAAATIgVAAIgGABQgGABgBAFQgCAFAAAHIAACoQAAATAFADQAEADAbABIAAATg");
	this.shape_19.setTransform(769.8,164.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AhFB+IAAgSIAYgCQAHAAAFgDQADgEAAgJIAAi6QAAgGgCgDQgDgCgJAAQgbAAgQAeQgJARgGAdIgSAAIAHhdIDkAAIAGBdIgSAAQgDgWgLgVQgRgigdABQgJAAgCAEQgBADAAAKIAAC2QgBALAGACQAFACAdAAIAAATg");
	this.shape_20.setTransform(1039.9,196.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("ABTB/IijjCIAACFQAAAYANAJQAHAGATAAIAAATIhkAAIAAgTQAZAAAGgKQAHgKAAggIAAiPIgGgGQgFgFgHgDIgHgDIgMgCIAAgRIBYAAICGCfIAAhpQAAgXgNgIQgIgFgSgBIAAgRIBjAAIAAARQgXADgHAJQgHALAAAbIAAC6g");
	this.shape_21.setTransform(1013.1,196.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("Ah3B+IAAgTQAZAAAFgCQAHgCAAgNIAAi3QAAgJgGgBQgEgCgbgBIAAgSIDoAAIADBaIgRABQgMgtgVgOQgWgOgfAAQgUgBgHAFQgHAFAAAPIAABGIAHAAQAZAAAMgTQAHgJADgVIASAAIAAB3IgRABQgDgggPgLQgPgKgWgBIAABRQAAAOAGADQAHAEAYAAQApAAAVgXQAMgOANgmIARABIgEBdg");
	this.shape_22.setTransform(984.6,196.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AAiB+IAAgTIAVgBQAJABADgHQACgFAAgEIAAjBIhMDkIgRAAIhQjgIAACfQAAAbAJAJQAJAKAUAAIAAATIhiAAIAAgTQASgBAGgFQAMgIABgYIAAicQAAgKgCgFQgDgDgMAAIgTgBIAAgSIBwAAIA2CXIA0iXIBuAAIAAASIgVABQgKgBgCAGQgCAEAAARIgBCjQAAANADAFQACAEALAAIAUABIAAATg");
	this.shape_23.setTransform(954.7,196.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("Ah7B+IAAgTIAUAAIAHgBQAGgBABgDQACgDAAgJIAAixQAAgNgFgDQgJgDgWAAIAAgSICUAAQAnABAUAJQAoAQAAAvQAAArgrARQgaAKgoAAIgngBIAABIQAAAJADAEQADADAKAAIAVABIAAATgAgShnQgGAEAAALIAABYIAGAAQArAAAMgGQAVgMAAglQAAgdgMgLQgMgLghAAQgOAAgFADg");
	this.shape_24.setTransform(925.7,196.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AhgBaQgigmAAg0QAAg4AngmQAmgkA1AAQA+AAAlArQAgAmAAAxQAAAyghAmQgmArg8AAQg5AAgngpgAg1hCQgJAYAAAtQAAArAOAhQANAjAlAAQAgAAAOgdQAOgeAAg3QAAgvgOghQgNgggiAAQgoAAgOAug");
	this.shape_25.setTransform(899.2,196.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("Ah2B+IAAgTIAUAAIAIgBQAEgBACgCQADgDAAgHIAAisQAAgTgDgDQgCgDgOgBIgSgBIAAgSICJAAIAAASIgaABQgJAAgBADQgCAEAAAGIAAC0QABAMAEADQAGAEASAAQAaAAAOgFQAPgEANgOQAJgLAGgRQAGgNACgLIASAAIgFBeg");
	this.shape_26.setTransform(872.4,196.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("Ah3B+IAAgTQAZAAAFgCQAGgCABgNIAAi3QAAgJgGgBQgEgCgbgBIAAgSIDoAAIADBaIgRABQgLgsgWgPQgWgOgfAAQgUgBgHAFQgHAFAAAPIAABGIAGAAQAaAAAMgTQAHgJADgVIASAAIAAB3IgRABQgDgggPgLQgPgKgWgBIAABRQAAAOAGADQAGAEAZAAQApAAAVgXQANgPALglIASABIgEBdg");
	this.shape_27.setTransform(846.9,196.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgQCAIhWjVQgGgPgGgDQgFgEgSgCIAAgSIB9AAIAAASIgWACIgFACQgCABAAAFIAAADIA7CWIA0iEIABgHQAAgOgNgFQgHgEgOgBIAAgSIBlAAIAAATQgPADgHAFQgPAMgKAYIhPDAg");
	this.shape_28.setTransform(820.4,197);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("Ah3B+IAAgTQAZAAAFgCQAHgCAAgNIAAi3QAAgJgGgBQgEgCgbgBIAAgSIDoAAIADBaIgRABQgLgsgWgPQgWgOgfAAQgUgBgHAFQgGAFAAAPIAABGIAGAAQAZAAANgTQAFgIAFgWIARAAIAAB3IgRABQgDgggPgLQgPgKgVgBIAABRQAAAOAFADQAHAEAYAAQAqAAAUgXQANgOALgmIASABIgEBdg");
	this.shape_29.setTransform(793.4,196.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AiGB+IAAgTIAWgBQAJAAADgDQACgEAAgIIAAizQAAgOgIgCQgDgCgIAAIgRAAIAAgSICaABQAzABAgAfQAgAiAAA4QAAAkgMAZQgLAZgSAPQgUAQgVAFQgVAEglABgAgehnQgGAEAAAJIAACuQABAOAEAFQAEAFATAAQAhAAARgPQAagaAAhBQAAhCgUgVQgUgVgiAAQgSAAgGADg");
	this.shape_30.setTransform(768.8,196.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AiGB9IAAgSIAXgBQAHAAAEgDQACgDAAgKIAAiyQABgNgJgDQgDgCgIAAIgRgBIAAgSICaABQA0ACAfAfQAgAiAAA5QAAAkgLAYQgNAZgRAPQgTAQgWAFQgWAFglgBgAgehmQgFADgBAJIAACuQAAAOAFAFQAEAFATgBQAhABARgPQAbgZAAhCQgBhBgUgWQgVgVghgBQgRAAgHAFg");
	this.shape_31.setTransform(879.5,228.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AApByQgOgNgCgWIgCgdQgCgYgHgMQgIgLgXAAIgWAAIAABUQAAAMADADQAEACAPAAIAQABIAAASIiIAAIAAgSQAZAAAEgCQAFgCACgLIAAiqQAAgSgCgFQgDgEgJgBIgWAAIAAgTICmABQAuACAUAYQAMAPAAAWQAAAjggAQQgQAIgaADQAOADAMAIQATAMAFAXIAIAfIAFAQQAEAIAFAAQAHgBADgHQAEgIADgSIARAAQAAAjgRANQgTAOgXAAQgaAAgNgOgAghhpQgFACgBAMIAABNQAtgBANgGQAXgKAAgjQgCgZgOgJQgNgIgXgBQgSAAgFAEg");
	this.shape_32.setTransform(851.6,229.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AARCAIAAgTIATgBQAIgDAAgHIgBgEIgRgqIhYAAIgFAMIgDAJQgCAGAAAGQAAAOAMAFQAHADAPACIAAATIhjAAIAAgTQARgDAJgJQAJgIANgeIBQi6IAZAAIBaDWQAGAOAFAEQAHAEAOAAIAAATgAg0AeIBFAAIgihVg");
	this.shape_33.setTransform(823.8,228.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AhfBaQgjgmAAg0QAAg4AngmQAmgkA1AAQA9AAAmArQAgAnAAAwQAAAxghAnQgmArg9AAQg5AAglgpgAg2hCQgHAZAAAsQAAAsANAgQANAjAlAAQAgAAAOgdQAOgcAAg5QAAgvgOghQgNgggiAAQgoAAgPAug");
	this.shape_34.setTransform(796.2,228.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("Ah8B9IAAgSIAVgBIAHgBQADgBADgCQACgCAAgGIAAi6QAAgHgDgCQgFgDgEgBIgKgBIgOAAIAAgTICWAAQAZAAAXAJQAnAQAAAkQAAAegZAOQgOAJgiAGQAiAFATAJQAgASAAAhQAAAUgNARQgNAQgTAGQgMADgLABQgSADglgBgAgaBaQAAALAEAEQAFACAPAAQAbAAAOgHQAUgMAAggQAAgfgVgMQgMgGgUgBIggAAgAgXhlQgDAEAAARIAABFIAngBQAJgCAHgEQALgGAFgMQAFgLAAgPQAAgcgTgLQgMgFgTAAQgSAAgFAFg");
	this.shape_35.setTransform(767.8,228.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#ED1C2E").ss(5.3,0,0,3.9).p("AnXkmQAAhJA0gzQAzg0BJAAIJPAAQBJAAAzA0QA0AzAABJIAAJNQAABJg0AzQgyA0hKAAIpPAAQhJAAgzg0Qg0gzAAhJg");
	this.shape_36.setTransform(693.5,196.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#ED1C2E").s().p("Aj4GEIAAlyQhWAAgUAAQgKAAgHgFQgIgGgBgHQgDgOAFgMIAFgIIFEk/IAWgTIAOgMQAGgEAHAAQAJAAAQARIAVASIB9B9QCKCJA/A5QAGAGADAKQADAMgDAJQgEAJgOAEQgKACgYAAIhWAAIgBFzgAALjvQgMADAAAZIAAIIICdgCIAAmrIhmhhQgPgOgGgFQgGgEgIAAIgIABg");
	this.shape_37.setTransform(693.5,194.7);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19,this.shape_20,this.shape_21,this.shape_22,this.shape_23,this.shape_24,this.shape_25,this.shape_26,this.shape_27,this.shape_28,this.shape_29,this.shape_30,this.shape_31,this.shape_32,this.shape_33,this.shape_34,this.shape_35,this.shape_36,this.shape_37];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_3, new cjs.Rectangle(643.7,146.6,619.1,99.4), null);


(lib.ClipGroup_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhTjAMPQhCAAgvgvQgvgvAAhCIAAzdQAAhCAvgvQAvgvBCAAMCnHAAAQBCAAAvAvQAvAvAABCIAATdQAABCgvAvQgvAvhCAAg");
	mask.setTransform(550.8,78.3);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#9C041C","#A1041B","#BB0117","#C50016"],[0,0.094,0.663,1],0,76.4,0,-76.3).s().p("EhWDAMPIAA4dMCsHAAAIAAYdg");
	this.shape.setTransform(550.8,78.3);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_2, new cjs.Rectangle(0,0,1101.7,156.6), null);


(lib.ClipGroup_0 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhWDAGbIAAs1MCsHAAAIAAM1g");
	mask.setTransform(550.8,41.1);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EhRGAGbQiDAAhdhdQhdhdAAiDIAAn4QDxB5JTBqQIsBkMfBLQL+BHNmAoQNjAoMtAAQMUAANegoQNkgoMDhHQMqhMIyhjQJfhqDwh5IAAH4QAACDhdBdQhcBdiEAAg");
	this.shape.setTransform(550.8,41.1);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_0, new cjs.Rectangle(0,0,1101.7,82.2), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAFBEIAAhoIANAAIAAAKQADgFAFgDQAGgEAIAAQANAAAKAJQAIALAAARQAAAYgNAKQgHAHgMAAQgIAAgGgDIgHgIIAAAngAAUgOQgDAHAAAKQAAAIADAGQAFAMANAAQAIAAAHgHQAFgHAAgPQAAgIgDgGQgEgNgNAAQgNAAgFANgAhKBEIAAhoIAMAAIAAAKQAEgFAFgDQAGgEAJAAQANAAAIAJQAJALAAARQAAAYgMAKQgJAHgLAAQgIAAgGgDIgIgIIAAAngAg7gOQgDAHAAAKQAAAIADAGQAEAMAOAAQAIAAAHgHQAFgHABgPQgBgIgDgGQgEgNgNAAQgOAAgEANgAjyAfQgLgKABgRIAMAAQABAJAEAGQAGAKARAAQAHAAAHgDQAMgEgBgLQAAgIgEgDQgGgEgKgCIgOgDQgNgDgGgEQgJgGAAgNQAAgOAJgJQAJgIARgBQAQABALAHQALAIAAARIgNAAQgBgIgDgFQgHgHgOgBQgMABgFAFQgFAFAAAGQAAAIAGADQAEADAOADIAOADQAKADAGAEQAJAHAAANQAAARgMAHQgMAHgQABQgTAAgKgKgAEwAeQgJgLAAgRQAAgSAKgMQAJgKAQgBQAPAAAJAKQAKAKAAASQAAASgJAMQgIALgTAAQgPAAgJgKgAE5gTQgFAJAAAMQAAALAFAJQAGAHALABQAMAAAEgKQAFgJAAgLQAAgLgDgGQgFgLgNAAQgLABgGAIgABbAeQgKgLAAgRQAAgSAKgMQAJgKARgBQAOAAAKAKQAKAKAAASQAAASgJAMQgIALgTAAQgPAAgJgKgABjgTQgEAJgBAMQABALAEAJQAGAHALABQANAAAEgKQAFgJgBgLQAAgLgCgGQgGgLgMAAQgMABgGAIgAiXAdQgCgGAAgKIAAgyIAMAAIAAAyQABAFABAEQADAGAKABQAMAAAFgNQACgFAAgLIAAglIAMAAIAABLIgLAAIAAgMIgGAHQgHAHgKAAQgQAAgGgLgADsAnQgJgBgDgEQgEgFAAgGIAAgxIgKAAIAAgLIAKAAIAAgUIAOAAIAAAUIALAAIAAALIgLAAIAAAwQgBAEADABIAFABIACAAIACAAIAAAKIgEABgAGBAmIAAhAIgLAAIAAgKIALAAIAAgMQAAgHACgEQAFgGAMgBIAFAAIAAAMIgEAAQgGAAgBADQgBADAAAMIAMAAIAAAKIgMAAIAABAgACoAmIAAhLIAMAAIAAAOQABgEAGgFQAFgGAIAAIABAAIADAAIAAAOIgEAAQgKAAgFAFQgFAHAAAIIAAAqgAlDAmIAAgvQAAgGgCgFQgEgGgJgBIgHACQgFABgEAEQgDAEgBAEIgBALIAAAnIgNAAIAAhLIAMAAIAAAMQAGgHAFgDQAHgDAHAAQAQAAAFALQADAGAAALIAAAwgAmZAmIAAhmIAOAAIAABmg");
	this.shape.setTransform(377.1,6.8);

	this.instance = new lib.ClipGroup_3();
	this.instance.parent = this;
	this.instance.setTransform(209.2,283.5,0.667,0.667,0,0,0,960,540);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-430.8,-76.5,1280,720);


(lib.Group = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.ClipGroup_0();
	this.instance.parent = this;
	this.instance.setTransform(550.8,41.1,1,1,0,0,0,550.8,41.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Group, new cjs.Rectangle(0,0,1101.7,82.2), null);


(lib.ClipGroup_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	mask.setTransform(960,540);

	// Layer_3
	this.instance = new lib.Group();
	this.instance.parent = this;
	this.instance.setTransform(960,741.7,1,1,0,0,0,550.8,41.1);
	this.instance.alpha = 0.102;

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#79011D").s().p("EhRGAOMQi3AAiCiBQiBiCAAi3IAAujQAAi3CBiBQCCiCC3AAMCiNAAAQC3AACCCCQCBCBAAC3IAAOjQAAC3iBCCQiCCBi3AAgEhUmgKyQhdBdAACEIAAOjQAACDBdBdQBdBdCDAAMCiNAAAQCEAABchdQBdhdAAiDIAAujQAAiEhdhdQhchciEAAMiiNAAAQiEAAhcBcg");
	this.shape.setTransform(960,704.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EBUngAJQhchdiEAAMiiNAAAQiDAAhdBdQhbBagCB/IAAhiQAAiDBdhdQBchcCEAAMCiNAAAQCEAABcBcQBdBdAACDIAABiQgCh/hbhag");
	this.shape_1.setTransform(960,646.9);

	var maskedShapeInstanceList = [this.instance,this.shape,this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup_1, new cjs.Rectangle(396.7,613.6,1126.7,181.6), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FCEE21").s().p("AgZCHQgagKgUgTQgTgTgKgaQgLgaAAghQgBgkAMgdQALgcAUgSQATgRAagKQAZgJAcAAQAmAAAVAPQAVAPgBAXQAAAKgEAKQgGALgGAFIgVgJQgOgEgNAAQgNAAgNAFQgMAEgHAJQgIAHgGAPQgGANABAQQgBAjAUARQAQASAcAAQASAAAKgEQAMgEAIgEQAKAIAGAJQAGAKAAAMQAAAXgWANQgUANgkAAQgiAAgagLg");
	this.shape.setTransform(683.8,63.8,0.667,0.667);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FCEE21").s().p("AggCKQgPgFgGgNIgphvIgPgvIgNguIgJgnQAHgIAMgGQANgFAPAAQARgBANAJQAMAIAGAWIAmCkIADAAIAVhcQAKgrAKg5QAKgFALgDQALgCALAAQASAAANAIQAMAIAAAVQAAALgEAQIgKAmQgHAagHAUIghBaIgPAhQgGAGgPAFQgOAEgTAAQgUAAgOgGg");
	this.shape_1.setTransform(665.6,63.9,0.667,0.667);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FCEE21").s().p("AgwCPQgSgDgOgHQgMgHgKgLQgHgKAAgPQAAgNAGgKQAFgLAHgFQAPAJAUAHQATAHAbAAQAPAAAJgFQAIgFAAgIQABgIgHgFQgHgFgNgCIgQgDQgtgKgXgVQgXgTAAgnQAAgUAJgSQAIgQAQgMQAQgMAVgFQATgHAaAAQAVAAAQADQATAEAMAGQALAFAJALQAHAKAAANQAAAOgFAJQgEAJgHAGIgNgGIgngKIgTgBQgPAAgKAEQgKAFAAAIQAAAGAGAEQAFAFAOADIAQAEQAzANAVAVQAWAUAAAjQAAArgeAZQgfAYg5AAQgYAAgSgEg");
	this.shape_2.setTransform(647.6,63.8,0.667,0.667);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FCEE21").s().p("AgnCJQgagJgUgTQgVgTgLgcQgLgdAAgkQAAglALgbQALgbATgRQASgRAYgJQAZgIAXAAQAcAAAXAJQAZAKAPAPQAQAPAKAXQAJAVAAAbQAAASgKAKQgKAKgSADIiBAVQAFATASAJQARAJAXAAQAVAAAVgFQARgGAOgIQAHAEAHALQAGALAAALQAAAagWAMQgSAKgUADQgUADgUAAQgfAAgagJgAgShGQgKAEgFAHQgFAHgEAJQgCAIgBAKIBZgQQgBgLgKgMQgLgLgTAAQgLAAgKAFg");
	this.shape_3.setTransform(629.1,63.8,0.667,0.667);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FCEE21").s().p("AhDAnIgHgRQgDgKAAgLQAAgUAJgKQAJgJAPAAIBwAAIAGAQQAEAKAAAMQAAAUgJAJQgKAKgOAAg");
	this.shape_4.setTransform(613.2,63.4,0.667,0.667);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FCEE21").s().p("AgnCJQgbgJgTgTQgVgTgLgcQgLgdAAgkQAAglALgbQAMgaASgSQATgSAXgIQAZgIAXAAQAcAAAXAJQAYAKAQAPQAQAPAJAXQAKAVAAAbQAAASgKAKQgLAKgRADIiBAVQAFASASAKQARAJAXAAQAWAAATgFQASgGANgIQAJAEAGALQAGAKgBAMQAAAagVAMQgRAKgVADQgUADgUAAQgfAAgagJgAgShGQgKAFgFAGQgFAGgDAKQgDAIgBAKIBZgQQgCgNgJgKQgKgLgUAAQgLAAgKAFg");
	this.shape_5.setTransform(597.3,63.8,0.667,0.667);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FCEE21").s().p("AgwCPQgTgDgNgHQgNgHgIgLQgIgKAAgPQAAgOAFgJQAGgKAHgGQARAKASAGQASAHAcAAQAQAAAIgFQAJgFAAgIQAAgIgHgFQgGgFgOgCIgQgDQgugKgWgVQgWgTAAgnQAAgVAIgRQAJgRAPgLQAPgLAVgGQAVgHAaAAQAUAAAQADQATAEALAGQAMAFAIALQAIAKAAANQAAAOgFAJQgFAKgGAFIgNgGIgSgFIgVgFIgSgBQgQAAgKAEQgKAEAAAJQAAAHAGADQAFAFAOADIAQAEQAzANAVAVQAVAVAAAiQAAArgeAZQgeAYg5AAQgYAAgSgEg");
	this.shape_6.setTransform(579.1,63.8,0.667,0.667);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FCEE21").s().p("AgyCNQgXgGgPgLQgQgLgJgSQgJgSAAgXQABgnAVgUQAVgUAugGIBFgIIAAgEQgBgQgNgHQgOgHgYAAQgUAAgTAEQgSAEgRAIQgHgGgEgKQgEgKgBgMQAAgPAHgIQAHgKANgFQAQgGAUgDQAWgDASAAQAZAAAaAGQAXAGARANQARANAJATQAIAUABAaIAAB+QAAAPgIAJQgIAKgKAGQgjAWg+AAQgaAAgYgFgAgBAbQgPABgKAGQgJAGAAALQAAALAIAHQAJAHASAAIAUgCQAMgCAEgDIAAgtg");
	this.shape_7.setTransform(560.3,63.8,0.667,0.667);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FCEE21").s().p("AgnCJQgagJgVgTQgUgTgKgcQgMgbAAgmQAAgmAMgaQAKgaATgSQATgSAYgIQAYgIAXAAQAcAAAXAJQAYAKAPAPQARAPAJAXQAKAXAAAZQAAASgKAKQgLAKgRADIiCAVQAGASASAKQARAJAXAAQAVAAAUgFQASgGAOgIQAHAEAHALQAFAKABAMQAAAagXAMQgSAKgUADQgTADgUAAQgeAAgbgJgAgShGQgKAFgFAGQgFAGgDAKQgEAKAAAIIBagQQgDgNgKgKQgJgLgUAAQgLAAgKAFg");
	this.shape_8.setTransform(541.5,63.8,0.667,0.667);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FCEE21").s().p("AhCAnQgFgIgCgJQgDgKAAgLQAAgUAJgKQAIgJAOAAIBxAAIAGAQQAEALAAALQgBAUgIAJQgKAKgOAAg");
	this.shape_9.setTransform(525.5,63.4,0.667,0.667);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FCEE21").s().p("AhEC2QgXgHgSgOQgXgRAAgdIAAkrIAQgFIAYgBQAIAAANABQAIACAIAFQAHAGACAIQADAJAAAOIAAA3QANgFAMgDQAOgCAMAAQAZAAAXAKQAWAJASATQASATAJAaQAKAZAAAlQAAAkgKAcQgKAbgTATQgSASgbAJQgaAKgggBQgiAAgZgJgAgbgWIgQAGIAAB6QAFAEAJADQAHACANAAQAYAAANgRQANgSAAgjQAAgkgNgQQgNgSgXAAQgLAAgIADg");
	this.shape_10.setTransform(509.3,60.8,0.667,0.667);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FCEE21").s().p("AgvC1QgagJgUgUQgSgUgLgaQgJgbAAgiQAAglAKgbQAKgaAUgTQATgSAYgJQAagJAcAAIAUACQALADAGACIAAhbIARgFIAXgBQAJAAAMABQAJACAHAFQAHAGACAIQADAJAAAOIAAELQAAAbgXAPQgRALgWAJQgYAHggAAQghAAgcgKgAgZgHQgPAQAAAkQAAAjAOASQAOARAaAAQAKAAAHgCQAHgEAFgDIAAh8QgKgHgPAAQgcAAgPASg");
	this.shape_11.setTransform(487.8,60.8,0.667,0.667);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FCEE21").s().p("ABBC8QgKgDgFgEQgGgFgEgJQgDgIAAgPIAAh+QAAgVgLgKQgLgJgPAAQgJAAgLACQgKAEgFADIAADFIgRAEQgLABgNAAIgUgBQgKgDgGgEQgHgGgDgIQgDgIAAgPIAAlHIARgDIAXgCQAJAAAMACQAJABAGAFQAGAFAEAJQAEALAAAMIAAA4IAUgHQAPgEAPAAQA0AAAeAcQAdAdAAA2IAACrIgQAEQgLABgNAAg");
	this.shape_12.setTransform(467.6,60.7,0.667,0.667);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FCEE21").s().p("AhNDdQgLgKAAgXQAAgRAEgOIBjmBIAPgCIANAAQAVAAAMAKQANAJAAAWQAAAQgFAPIhjGDIgbACQgWAAgNgKg");
	this.shape_13.setTransform(451.2,61.7,0.667,0.667);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FCEE21").s().p("AhRCzQgcgOAAgfQAAgNAFgKQAGgLAGgEQAOAIAUAIQAUAFAUAAQAbAAASgKQAQgKAAgWIAAgJQgVAKgeAAQgXAAgXgIQgUgIgRgQQgQgQgKgZQgKgYAAgkQAAgiALgaQAKgZASgQQARgRAagIQAbgJAbAAQAdAAAaAJQAYAHARANQALAJAGAJQAGAKAAAPIAADFQAAAegLAWQgKAVgSAPQgTAOgYAHQgaAHgaAAQgvAAgcgOgAgZhlQgMAQAAAcQAAAhAMAOQAOAOASAAQAWAAANgKIAAhoIgLgEQgGgDgMAAQgYAAgOAQg");
	this.shape_14.setTransform(434.8,67,0.667,0.667);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FCEE21").s().p("AgwCPQgTgDgNgHQgNgHgJgLQgHgKAAgPQAAgOAFgJQAGgKAHgGQARAKASAGQASAHAcAAQAPAAAJgFQAIgFAAgIQABgIgHgFQgGgFgOgCIgQgDQgvgKgVgVQgXgTAAgnQABgVAHgRQAKgRAOgLQAPgLAWgGQAVgHAZAAQAVAAAQADQASAEAMAGQAMAFAIALQAIAKAAANQgBAOgEAJQgFAKgHAFIgMgGIgTgFIgUgFIgTgBQgPAAgLAEQgJAEAAAJQAAAHAGADQAFAFAOADIAQAEQAzANAVAVQAVAVAAAiQABArgfAZQgeAYg6AAQgXAAgSgEg");
	this.shape_15.setTransform(416.7,63.8,0.667,0.667);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FCEE21").s().p("AglAnQgNgPAAgYQAAgXANgQQAOgPAXAAQAYAAAOAPQANAQAAAXQAAAYgNAPQgOAQgYAAQgXAAgOgQg");
	this.shape_16.setTransform(403.7,69.9,0.667,0.667);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FCEE21").s().p("AggCKQgPgFgGgNIgLgbIgOgmIgQguIgPgvIgNguIgJgnQAHgIANgGQAMgFAPAAQARgBANAJQAMAHAGAXIAUBXIAMAtIAGAgIADAAIAVhcQAKgrAKg5QAKgFALgDQALgCALAAQASAAANAIQAMAIAAAVQAAALgEAQIgKAmQgHAagHAUIghBaIgPAhQgGAGgPAFQgOAEgTAAQgUAAgOgGg");
	this.shape_17.setTransform(389.8,63.9,0.667,0.667);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FCEE21").s().p("Ag4CIQgagLgRgSQgSgTgLgbQgKgcAAghQAAggAKgcQALgbASgTQATgTAYgKQAagKAeAAQAfAAAaAKQAZALASATQASASALAcQAJAbABAgQgBAjgJAbQgKAbgTATQgSATgZAKQgaAJgfAAQgdAAgbgKgAghgzQgMASgBAhQAAAiANATQANASAUAAQAWAAAMgTQANgSAAgiQAAghgNgSQgLgTgXAAQgVAAgMATg");
	this.shape_18.setTransform(370,63.8,0.667,0.667);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FCEE21").s().p("AhRCzQgcgOAAgfQAAgNAFgKQAGgLAGgEQAOAIAUAIQAUAFAUAAQAbAAASgKQAQgKAAgWIAAgJQgVAKgeAAQgXAAgXgIQgUgIgRgQQgQgQgKgZQgKgYAAgkQAAgiALgaQAKgZASgQQARgRAagIQAbgJAbAAQAdAAAaAJQAYAHARANQALAJAGAJQAGAKAAAPIAADFQAAAegLAWQgKAVgSAPQgTAOgYAHQgaAHgaAAQgvAAgcgOgAgZhlQgMAQAAAcQAAAhAMAOQAOAOATAAQAVAAANgKIAAhoIgLgEQgGgDgMAAQgYAAgOAQg");
	this.shape_19.setTransform(349.2,67,0.667,0.667);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FCEE21").s().p("AglAnQgNgPAAgYQAAgXANgQQAOgPAXAAQAYAAAOAPQANAQAAAXQAAAYgNAPQgOAQgYAAQgXAAgOgQg");
	this.shape_20.setTransform(335.5,69.9,0.667,0.667);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FCEE21").s().p("Ag4CIQgagLgRgSQgSgTgLgbQgJgcgBghQABggAJgcQALgbASgTQATgTAYgKQAagKAeAAQAfAAAZAKQAaALASATQATASAKAcQAKAbgBAgQABAjgKAbQgKAbgTATQgSATgaAKQgYAJggAAQgeAAgagKgAghgzQgMASAAAhQAAAiAMATQAMASAWAAQAVAAANgTQALgSABgiQgBghgLgSQgMgTgXAAQgVAAgMATg");
	this.shape_21.setTransform(321,63.8,0.667,0.667);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FCEE21").s().p("AhRCzQgcgOAAgfQAAgNAFgKQAGgLAGgEQAOAIAUAIQAUAFAUAAQAbAAASgKQAQgKAAgWIAAgJQgVAKgeAAQgXAAgXgIQgUgIgRgQQgRgRgJgYQgKgYAAgkQAAgiALgaQAKgZASgQQARgRAagIQAbgJAbAAQAdAAAaAJQAYAHARANQALAJAGAJQAGAKAAAPIAADFQAAAegLAWQgKAVgSAPQgTAOgYAHQgaAHgaAAQgvAAgcgOgAgZhlQgMAQAAAcQAAAhAMAOQAOAOASAAQAWAAANgKIAAhoQgEgDgHgBQgGgDgMAAQgYAAgOAQg");
	this.shape_22.setTransform(300.2,67,0.667,0.667);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AglCAQgNgPAAgYQAAgYANgQQAOgPAXAAQAYAAANAPQAOARAAAXQAAAXgOAQQgNAQgYAAQgYAAgNgQgAglgwQgNgQAAgYQAAgXANgQQAOgQAXAAQAYAAANAQQAOAQAAAXQAAAXgOARQgNAQgYAAQgYAAgNgQg");
	this.shape_23.setTransform(272,64,0.667,0.667);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag5CWQgZgXAAgzIAAjxIAQgEIAXgCQAXAAANAJQANAJAAAcIAAAkIBEAAIAGAPQADALAAAKQAAAUgIAJQgIAJgOgBIgvAAIAABVQgBAQAJAFQAJAGAPAAIARgBIAPgEIAIAOQADAHAAALQABAWgQAOQgPANgmAAQgtAAgZgWg");
	this.shape_24.setTransform(260.9,62.1,0.667,0.667);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgyCNQgXgGgPgLQgQgLgJgSQgJgSAAgXQABgnAVgUQAVgUAugGIBFgIIAAgEQAAgQgOgHQgOgHgYAAQgUAAgTAEQgRAEgRAIQgIgGgEgKQgFgLAAgLQAAgOAHgJQAGgJAOgGQAQgGAUgDQAWgDARAAQAaAAAaAGQAXAGARANQAQANAKATQAIAUABAaIAAB+QAAAPgIAJQgIAJgKAHQgkAWg9AAQgaAAgYgFgAgBAbQgPABgKAGQgJAGAAALQAAALAIAHQAJAHASAAIAUgCQAMgCAEgDIAAgtg");
	this.shape_25.setTransform(243.4,63.8,0.667,0.667);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAnB4IgkiIIgkCRQgHAFgOAFQgLAEgTABQgWAAgPgHQgQgGgFgMQgGgNgIgeIgdiHQgHglgDgbQAHgIANgGQAMgFAPAAQASgBAMAKQAMAHADAWIAVCfIACAAIAmikQAJgGALgEQAKgDAPAAQASAAAOAGQANAGAEAOIAkCXIADAAIAVi6QAKgGAKgDQAMgCAKAAQASAAAMAIQAMAIAAAVQAAANgCAOIgHApIgKAvIgWBaIgIAdQgHAGgQAEQgOAEgTABQgsgBgIgXg");
	this.shape_26.setTransform(213.2,63.9,0.667,0.667);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("Ag4CIQgagLgRgSQgSgTgLgbQgKgcABghQgBggAKgcQALgbASgTQATgTAYgKQAagKAeAAQAfAAAaAKQAYALATATQASASALAcQAJAbABAgQgBAjgJAbQgKAbgTATQgSATgZAKQgaAJgfAAQgdAAgbgKgAgigzQgLASgBAhQAAAiANATQANASAUAAQAXAAALgTQAMgSAAgiQAAghgMgSQgMgTgWAAQgVAAgNATg");
	this.shape_27.setTransform(189,63.8,0.667,0.667);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("ABBCPQgJgDgGgEQgHgGgDgJQgDgHAAgPIAAiFQAAgRgKgJQgIgHgRgBQgIAAgMADQgJADgIAGIAADDIgRAEQgLABgMAAIgVgBQgLgDgFgEQgGgFgEgKQgDgJAAgNIAAipQAAgPAGgKQAHgKAKgIQARgMAcgJQAcgJAfAAQA8AAAgAcQAgAdAAAxIAACwIgQAEQgLABgNAAg");
	this.shape_28.setTransform(168.4,63.7,0.667,0.667);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhSCwQgOgOgCgXQAVgTAMgMQAQgPAPgUQgIgDgLgLQgLgKgMgdIgMgfQgHgQgHgYQgHgUgIgfIgQhDQAHgIAMgGQAOgGAOAAQASAAANAIQALAIAHAXIAoCaIACAAIANgpIAfiNQATgLAXAAQASAAAMAIQANAIAAAWQAAAOgEAVQgFAYgFATQgEATgKAbIgjBaIgTAlQgPAcgMASQgNARgMAKQgKAKgMAEQgLADgNAAQgWAAgOgOg");
	this.shape_29.setTransform(141.3,67,0.667,0.667);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgQC8QgJgDgGgEQgHgGgDgIQgDgIAAgPIAAlHIARgDIAXgCQAIAAAMACQAJABAHAFQAFAFAFAJQADALAAAMIAAFHIgSADQgJACgNAAg");
	this.shape_30.setTransform(126.8,60.7,0.667,0.667);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhnC+QgJgBgHgFQgGgGgDgIQgEgLAAgMIAAkPQAAgOAHgKQAFgJALgJQARgLAYgHQAZgHAdAAQAfAAAbAJQAbAJAUASQAUASALAbQALAbAAAmQAAAmgKAZQgJAbgSASQgSAUgYAIQgYAJgeAAQgWAAgUgHIAABdIgRAEQgKACgNAAgAgchxQgIACgGAEIAAB7IAOAGQAGACAJAAQA2AAAAhFQAAgjgOgSQgNgSgZAAQgLAAgGADg");
	this.shape_31.setTransform(111.9,66.9,0.667,0.667);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AhnC+QgJgBgHgFQgGgGgDgIQgEgJAAgOIAAkPQAAgPAGgJQAFgJAMgJQARgLAYgHQAZgHAdAAQAfAAAbAJQAbAJAUASQAUATALAaQALAdAAAkQAAAkgKAbQgJAbgSASQgSAUgYAIQgYAJgeAAQgWAAgUgHIAABdIgRAEQgKACgNAAgAgdhxQgHADgGADIAAB7IANAGQAHACAJAAQA2AAAAhFQAAgjgOgSQgNgSgZAAQgLAAgHADg");
	this.shape_32.setTransform(91.3,66.9,0.667,0.667);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("ABVCvQgJgDgGgEQgGgFgDgHQgDgGgCgLIgKgnIhfAAIgRBGIgQAFQgHACgMAAQgcAAgMgKQgNgKAAgRQAAgJACgHIAFgTIAKglIBJjkQAKgGARgFQAUgFARAAQAZAAAVAJQAVAIAFARIAVBEIA+DpQgFAIgOAGQgNAEgRAAQgOAAgHgCgAgRgiQgJAagHAgIBAAAIgdhvIgDAAg");
	this.shape_33.setTransform(69.7,61.6,0.667,0.667);

	this.instance = new lib.ClipGroup_1();
	this.instance.parent = this;
	this.instance.setTransform(375.6,-49,0.667,0.667,0,0,0,960,540);

	this.instance_1 = new lib.ClipGroup_2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(375.5,60.6,0.667,0.667,0,0,0,550.8,78.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-264.4,-409,1280,720);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_2 = function() {
		this.parent.playSfx();
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(2).call(this.frame_2).wait(27).call(this.frame_29).wait(1));

	// logo
	this.instance = new lib.Symbol1("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.1,-12.5,1,1,0,0,0,209.2,283.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:0,alpha:1},15,cjs.Ease.get(1)).wait(15));

	// title
	this.instance_1 = new lib.Symbol2("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-6.2,-94.5,1,1,0,0,0,390.8,59.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-82,alpha:1},15,cjs.Ease.get(1)).wait(15));

	// btn
	this.instance_2 = new lib.Symbol3("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(0.1,-12.5,1,1,0,0,0,375.6,-49.1);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:0,alpha:1},15,cjs.Ease.get(1)).wait(15));

	// note
	this.instance_3 = new lib.Symbol4("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(-3,244.5,1,1,0,0,0,378.6,25.8);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:232,alpha:1},15,cjs.Ease.get(1)).wait(15));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFDD").s().p("EiV/BUYMAAAiovMEr/AAAMAAACovg");
	this.shape.setTransform(0,0,0.667,0.667);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-640,-360,1280,720);


// stage content:
(lib.scene12 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		createjs.Touch.enable(stage, true, true);
		
		var audioPath = "audio/";
		var sounds = [
			{src:{mp3:"transition.mp3", ogg:"transition.ogg"}, id:"sfx1"}
		 ];
			
		createjs.Sound.alternateExtensions = ["mp3"];    // if the passed extension is not supported, try this extension
		createjs.Sound.on("fileload", handleLoad); // call handleLoad when each sound loads
		createjs.Sound.registerSounds(sounds, audioPath);
		
		function handleLoad(e) {
			if (e.id == "audio_notification") {
				//createjs.Sound.play("audio_bgmusic");
			}
		}
		
		
		this.playSfx = function () {
			createjs.Sound.play("sfx1");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer_1
	this.mc_main = new lib.Symbol5();
	this.mc_main.parent = this;
	this.mc_main.setTransform(640,360);

	this.timeline.addTween(cjs.Tween.get(this.mc_main).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(640,347.5,1280,732.5);
// library properties:
lib.properties = {
	id: '5CCB8819BBFC41AFB90D02C4CC889A07',
	width: 1280,
	height: 720,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['5CCB8819BBFC41AFB90D02C4CC889A07'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;